/**
 * 艺术风格矩阵数据集 (Art Style Matrix Database)
 * 涵盖 3 大基准测试场景 × 14 种经典艺术与插画流派 (全 42 组完整出图与视觉图谱)
 */

const STYLE_CATEGORIES = [
  { id: 'all', name: '全部风格', icon: 'sparkles' },
  { id: 'fine_art', name: '传统画种与质感', icon: 'palette', desc: '注重颜料厚度、笔触肌理与光影层次' },
  { id: 'printmaking', name: '版画与印刷媒介', icon: 'printer', desc: '强调套印对位、网点网纹与分明色块' },
  { id: 'retro_pop', name: '时代美学与潮流', icon: 'disc', desc: '融合时代符号、几何曲线与复古光泽' },
  { id: 'digital', name: '现代数码与概念', icon: 'monitor', desc: '兼具矢量极简、赛璐珞光影与点阵趣味' }
];

const SCENES_DATA = [
  {
    id: 'scene_a',
    title: '场景 A · 咖啡馆女性与猫',
    subtitle: '人物与生活情境 · 肖像与氛围光影测试',
    badge: '3:4 肖像比例',
    description: '咖啡馆雨窗旁，戴宽檐帽喝咖啡的优雅女性，木桌上趴着一只睡猫。用于测试人物五官结构、衣褶质感、室内外冷暖对比与情绪传达。',
    coreSubject: 'A stylish woman in a wide-brim hat sitting by a rainy cafe window, sipping coffee, a fluffy cat sleeping on the wooden table',
    aspectRatio: '3:4',
    styles: [
      {
        id: 'scene_a_01_impasto',
        number: '01',
        nameCn: '厚涂油画',
        nameEn: 'Impasto Oil Painting',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_a_01_impasto.jpg',
        hasImage: true,
        tags: ['颜料堆叠', '油画刀刮痕', '明暗对比', '厚重体积'],
        master: 'Craig Mullins / 梵高 / 伦勃朗',
        colorTone: '浓郁赭石、普鲁士蓝与暖灯金光',
        technique: '使用厚重油彩与油画刀层叠涂抹，强调厚重物理肌理与雕塑般的形体转折。',
        prompt: 'Impasto oil painting of a stylish woman in a wide-brim hat sitting by a rainy cafe window, sipping coffee, a fluffy cat sleeping on the wooden table, thick visible palette knife strokes, heavy textured oil paint, rich chiaroscuro lighting, Craig Mullins style --ar 3:4',
        keyModifiers: ['impasto oil painting', 'thick visible palette knife strokes', 'heavy textured oil paint', 'rich chiaroscuro lighting', 'Craig Mullins style']
      },
      {
        id: 'scene_a_02_watercolor',
        number: '02',
        nameCn: '通透水彩',
        nameEn: 'Luminous Watercolor',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_a_02_watercolor.jpg',
        hasImage: true,
        tags: ['湿画晕染', '边缘渗色', '水光透明', '冷压纸纹'],
        master: 'Sargent / 现代水彩插画',
        colorTone: '焦茶色毛衣、水色蓝灰与暖橙街灯',
        technique: '利用水分在粗纹水彩纸上的自然扩散与留白，形成半透明的色彩交融与雨水流动感。',
        prompt: 'Luminous watercolor painting of a stylish woman in a wide-brim hat sitting by a rainy cafe window, sipping coffee, a fluffy cat sleeping on the wooden table, wet-on-wet bleeding washes, translucent watercolor pigments, visible cold-press paper grain, delicate soft ink lines --ar 3:4',
        keyModifiers: ['luminous watercolor painting', 'wet-on-wet bleeding washes', 'translucent watercolor pigments', 'visible cold-press paper grain', 'delicate soft ink lines']
      },
      {
        id: 'scene_a_03_impressionism',
        number: '03',
        nameCn: '印象派与点彩',
        nameEn: 'Impressionist Oil',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_a_03_impressionism.jpg',
        hasImage: true,
        tags: ['瞬时光影', '颤动笔触', '色彩并置', '空气透视'],
        master: '莫奈 (Monet) / 皮萨罗 (Pissarro)',
        colorTone: '钴蓝大衣、草编草帽金黄与暖色室内灯火',
        technique: '以碎小跳跃的纯色笔触并置，利用人眼视觉混合产生光彩闪烁的颤动感。',
        prompt: 'Impressionist oil painting of a stylish woman in a wide-brim hat sitting by a rainy cafe window, sipping coffee, a fluffy cat sleeping on the wooden table, loose flickering brushstrokes, Claude Monet style, vibrant unmixed color vibration, dappled ambient light --ar 3:4',
        keyModifiers: ['impressionist oil painting', 'loose flickering brushstrokes', 'Claude Monet style', 'vibrant unmixed color vibration', 'dappled ambient light']
      },
      {
        id: 'scene_a_04_silkscreen',
        number: '04',
        nameCn: '丝网版画 / 波普艺术',
        nameEn: 'Silkscreen / Pop Art',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_a_04_silkscreen.jpg',
        hasImage: true,
        tags: ['对位错版', '高饱和平涂', '粗颗粒网点', '波普海报'],
        master: '安迪·沃霍尔 (Andy Warhol)',
        colorTone: '青蓝、明黄与荧光洋红的剧烈对撞',
        technique: '模拟手工丝网多层孔版套印，带有标志性的边缘微错位与印刷漏色质感。',
        prompt: 'Silkscreen screenprint pop art of a stylish woman in a wide-brim hat sitting by a rainy cafe window, sipping coffee, a fluffy cat sleeping on the wooden table, bold flat color blocks, slight misregistration print offset, Andy Warhol graphic poster aesthetic --ar 3:4',
        keyModifiers: ['silkscreen screenprint pop art', 'bold flat color blocks', 'slight misregistration print offset', 'Andy Warhol graphic poster aesthetic']
      },
      {
        id: 'scene_a_05_ukiyoe',
        number: '05',
        nameCn: '浮世绘木刻版画',
        nameEn: 'Japanese Ukiyo-e',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_a_05_ukiyoe.jpg',
        hasImage: true,
        tags: ['黑墨勾线', '矿物颜料平涂', '和纸纤维', '散点构图'],
        master: '葛饰北斋 / 歌川广重',
        colorTone: '深青花和服、浅土黄木构与和纸米白',
        technique: '严谨克制的木刻雕版墨线，搭配传统矿物植物颜料的大面积平涂与木质拓印感。',
        prompt: 'Authentic Japanese Ukiyo-e woodblock print of a stylish woman in a wide-brim hat sitting by a rainy cafe window, sipping coffee, a sleeping cat on the wooden table, crisp black sumi-e outlines, flat mineral pigment washes, washi paper texture, Hokusai style --ar 3:4',
        keyModifiers: ['Japanese Ukiyo-e woodblock print', 'crisp black sumi-e outlines', 'flat mineral pigment washes', 'washi paper texture', 'Hokusai style']
      },
      {
        id: 'scene_a_06_vintage_comic',
        number: '06',
        nameCn: '美漫复古网点',
        nameEn: 'Vintage Comic / Ben-Day Dots',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_a_06_vintage_comic.jpg',
        hasImage: true,
        tags: ['本戴网点', '四色套印', '墨线硬边', '漫画对话框'],
        master: '罗伊·利希滕斯坦 (Roy Lichtenstein)',
        colorTone: 'CMYK 原色体系（纯黄、纯红、深黑与网点青）',
        technique: '20世纪60年代美漫低成本印刷工艺，利用密集的原色小圆点并置形成灰阶与阴影。',
        prompt: 'Vintage 1960s comic book illustration of a stylish woman in a wide-brim hat sitting by a rainy cafe window, sipping coffee, a cat sleeping on the table, Roy Lichtenstein style, prominent Ben-Day halftone dots, bold black ink contour lines, aged pulp paper texture --ar 3:4',
        keyModifiers: ['vintage 1960s comic book illustration', 'Roy Lichtenstein style', 'prominent Ben-Day halftone dots', 'bold black ink contour lines', 'aged pulp paper texture']
      },
      {
        id: 'scene_a_07_citypop',
        number: '07',
        nameCn: 'City Pop 昭和复古',
        nameEn: '1980s City Pop Aesthetic',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_a_07_citypop.jpg',
        hasImage: true,
        tags: ['粉紫晚霞', '几何硬影', '霓虹招牌', '都市假日感'],
        master: '永井博 (Hiroshi Nagai) / 铃木英人',
        colorTone: '海蓝、粉紫渐变晚霞、鹅黄与翠绿',
        technique: '80年代日本黑胶唱片封套美学，干净明快的色块过渡，几何化的扁平硬阴影与复古度假氛围。',
        prompt: '1980s Japanese City Pop aesthetic illustration by Hiroshi Nagai and Eizin Suzuki, a stylish woman in a wide-brim hat sitting by a cafe window, sipping coffee, a cat sleeping on the table, vibrant pastel sky gradients, clean flat shadows, retro 80s album cover vibe --ar 3:4',
        keyModifiers: ['1980s Japanese City Pop aesthetic', 'Hiroshi Nagai style', 'Eizin Suzuki style', 'vibrant pastel sky gradients', 'clean flat shadows']
      },
      {
        id: 'scene_a_08_artnouveau',
        number: '08',
        nameCn: '新艺术运动',
        nameEn: 'Art Nouveau Masterpiece',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_a_08_artnouveau.jpg',
        hasImage: true,
        tags: ['自然藤蔓线', '植物花卉边框', '金箔装饰', '石版画优雅'],
        master: '阿尔丰斯·慕夏 (Alphonse Mucha)',
        colorTone: '复古烫金、橄榄绿、鸢尾紫与象牙白',
        technique: '19世纪末世纪之交的有机曲线美学，将女性柔美卷发、植物花藤与华丽的对称装饰框融为一体。',
        prompt: 'Art Nouveau masterpiece illustration of a stylish woman in a wide-brim hat sitting by a cafe window, sipping coffee, a sleeping cat, Alphonse Mucha style, flowing sinuous organic lines, intricate floral decorative borders, golden foil accents, elegant lithograph --ar 3:4',
        keyModifiers: ['Art Nouveau masterpiece illustration', 'Alphonse Mucha style', 'flowing sinuous organic lines', 'intricate floral decorative borders', 'golden foil accents']
      },
      {
        id: 'scene_a_09_artdeco',
        number: '09',
        nameCn: '装饰风艺术',
        nameEn: 'Art Deco Luxury',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_a_09_artdeco.jpg',
        hasImage: true,
        tags: ['机械几何', '放射状对称', '黑金奢华', '流线型轮廓'],
        master: '塔玛拉·德·蓝披卡 (Tamara de Lempicka)',
        colorTone: '曜石黑、香槟金、黄铜与深宝蓝',
        technique: '1920年代盖茨比时期的现代工业奢华，以折线、弧线、几何硬切面与金属光泽构建锐利的高级感。',
        prompt: 'Art Deco illustration of a glamorous woman in a wide-brim hat sitting by a rainy cafe window, sipping coffee, a sleeping cat, sleek geometric symmetry, sharp streamlined shapes, luxurious gold and obsidian palette, Tamara de Lempicka 1920s aesthetic --ar 3:4',
        keyModifiers: ['Art Deco illustration', 'sleek geometric symmetry', 'sharp streamlined shapes', 'luxurious gold and obsidian palette', 'Tamara de Lempicka 1920s aesthetic']
      },
      {
        id: 'scene_a_10_cyberpunk',
        number: '10',
        nameCn: '赛博朋克霓虹',
        nameEn: 'Cyberpunk Neon',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_a_10_cyberpunk.jpg',
        hasImage: true,
        tags: ['全息霓虹', '雨雾光晕', '机械改造猫', '高科技低生活'],
        master: '《银翼杀手》 / Syd Mead',
        colorTone: '电光青 (Cyan)、荧光洋红 (Magenta) 与深黑',
        technique: '高对比度的自发光体与湿漉沥青的反光交织，冷调雨夜与暖调全息看板的极度反差。',
        prompt: 'Cyberpunk neon illustration of a woman in a wide-brim hat sitting by a rain-streaked cafe window overlooking a futuristic neon megacity, glowing cyan and magenta reflections, steaming coffee, a cybernetic cat on the table, volumetric rain haze, Blade Runner style --ar 3:4',
        keyModifiers: ['Cyberpunk neon illustration', 'glowing cyan and magenta reflections', 'cybernetic cat', 'volumetric rain haze', 'Blade Runner style']
      },
      {
        id: 'scene_a_11_ghibli',
        number: '11',
        nameCn: '吉卜力 / 赛璐珞平涂',
        nameEn: 'Studio Ghibli / Cel Anime',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_a_11_ghibli.jpg',
        hasImage: true,
        tags: ['手绘水粉背景', '清晰硬阴影', '温馨治愈', '日系暖调'],
        master: '男鹿和雄 (Kazuo Oga) / 宫崎骏',
        colorTone: '原木暖褐、米白针织毛衣与三花猫暖色',
        technique: '经典动画手绘工序：前景人物采用干净利落的赛璐珞硬阴影，背景采用细腻写实的水粉风景画。',
        prompt: 'Anime cel-shaded illustration in the style of Studio Ghibli, a cozy woman in a hat sitting by a rain-streaked cafe window, sipping coffee, a sleeping cat on the table, hand-painted Kazuo Oga background, clean cel shadows, warm and nostalgic atmosphere --ar 3:4',
        keyModifiers: ['Anime cel-shaded illustration', 'Studio Ghibli style', 'hand-painted Kazuo Oga background', 'clean cel shadows', 'warm and nostalgic']
      },
      {
        id: 'scene_a_12_flatvector',
        number: '12',
        nameCn: '极简扁平矢量',
        nameEn: 'Minimalist Flat Vector',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_a_12_flatvector.jpg',
        hasImage: true,
        tags: ['负空间构图', '纯粹色块', '无渐变硬边', '时尚杂志海报'],
        master: 'Malika Favre',
        colorTone: '克莱因蓝、暖焦糖色、纯白与深黑',
        technique: '极度克制的视觉语言，摒弃所有噪点与过渡，用极致精准的几何形体和巧妙的负空间构建张力。',
        prompt: 'Minimalist flat vector graphic illustration by Malika Favre, a woman in a wide-brim hat sitting by a cafe window with a cup of coffee and a cat, bold geometric color blocks, brilliant negative space design, razor-sharp clean edges, high-fashion poster --ar 3:4',
        keyModifiers: ['Minimalist flat vector graphic illustration', 'Malika Favre style', 'bold geometric color blocks', 'brilliant negative space design', 'razor-sharp clean edges']
      },
      {
        id: 'scene_a_13_pixelart',
        number: '13',
        nameCn: '16-bit 像素风',
        nameEn: '16-bit Pixel Art',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_a_13_pixelart.jpg',
        hasImage: true,
        tags: ['点阵颗粒', '抖动渐变 (Dithering)', '复古UI面板', '街机复古'],
        master: 'SNES 黄金时代像素大师',
        colorTone: '红砖暖褐、钨丝灯暖黄与雨巷青蓝',
        technique: '基于严谨像素网格的手工点阵绘制，利用 Dithering（网点交错）模拟光线过渡，附带经典游戏 HUD 计分板。',
        prompt: '16-bit pixel art of a cozy woman in a hat sitting by a rainy cafe window drinking coffee, a fluffy cat sleeping on the wooden table, warm glowing indoor lights, meticulous pixel dithering, nostalgic retro 90s SNES video game aesthetic --ar 3:4',
        keyModifiers: ['16-bit pixel art', 'meticulous pixel dithering', 'retro 90s SNES video game aesthetic', 'warm glowing indoor lights']
      },
      {
        id: 'scene_a_14_crayon',
        number: '14',
        nameCn: '绘本蜡笔与拼贴',
        nameEn: 'Picture Book / Crayon Collage',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_a_14_crayon.jpg',
        hasImage: true,
        tags: ['蜡笔笔触', '油画棒颗粒', '手撕纸拼贴', '童趣质朴'],
        master: 'Eric Carle / Oliver Jeffers',
        colorTone: '暖土黄、草木绿与柔和粉蜡',
        technique: '模拟儿童绘本的手工质感，凹凸不平的蜡质肌理与剪纸边缘，散发纯真与治愈感。',
        prompt: 'Whimsical children\'s picture book illustration of a gentle woman in a wide-brim hat at a rainy cafe window with a sleeping cat and coffee, visible waxy crayon strokes, soft oil pastel texture, torn paper collage layers, Eric Carle and Oliver Jeffers style --ar 3:4',
        keyModifiers: ['children\'s picture book illustration', 'visible waxy crayon strokes', 'soft oil pastel texture', 'torn paper collage layers', 'Eric Carle style']
      }
    ]
  },
  {
    id: 'scene_b',
    title: '场景 B · 雨后黄昏海滨电车',
    subtitle: '城市与建筑街景 · 空间透视与倒影测试',
    badge: '16:9 全景比例',
    description: '雨后黄昏的海滨街口，一辆复古黄色有轨电车驶过，路面水洼倒影与路灯。用于测试透视线条、建筑几何、反光倒影、冷暖色彩与时代感。',
    coreSubject: 'A coastal city street intersection at twilight after rain, a vintage yellow tram passing on rails, glowing street lamps, wet reflections on asphalt, ocean horizon',
    aspectRatio: '16:9',
    styles: [
      {
        id: 'scene_b_01_impasto',
        number: '01',
        nameCn: '厚涂油画',
        nameEn: 'Impasto Oil Painting',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_b_01_impasto.jpg',
        hasImage: true,
        tags: ['厚重刮刀', '湿路反光', '暮色苍茫'],
        master: 'Craig Mullins / 伦勃朗',
        colorTone: '深焦糖、赭石与街灯金光',
        technique: '厚重刮刀堆叠沥青路面水光反光，富有雕塑感。',
        prompt: 'Impasto oil painting of a coastal city street intersection at twilight after rain, a vintage yellow tram on rails, glowing street lamps, wet reflections on asphalt, thick expressive palette knife strokes, heavy oil texture, rich dramatic evening light --ar 16:9',
        keyModifiers: ['Impasto oil painting', 'thick expressive palette knife strokes', 'heavy oil texture', 'rich dramatic evening light']
      },
      {
        id: 'scene_b_02_watercolor',
        number: '02',
        nameCn: '通透水彩',
        nameEn: 'Luminous Watercolor',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_b_02_watercolor.jpg',
        hasImage: true,
        tags: ['湿画水滩', '光晕弥散', '轻灵通透'],
        master: 'Alvaro Castagnet / 现代水彩',
        colorTone: '水色青蓝、路面湿润倒影与柔和光晕',
        technique: '湿画法表现地面积水漫反射与海风吹拂的朦胧感。',
        prompt: 'Luminous watercolor painting of a coastal city street intersection at twilight after rain, a vintage yellow tram passing, glowing street lamps, wet-on-wet bleeding washes, delicate puddles with soft reflections, visible cold-press paper grain, poetic and breezy --ar 16:9',
        keyModifiers: ['Luminous watercolor painting', 'wet-on-wet bleeding washes', 'delicate puddles with soft reflections', 'visible cold-press paper grain']
      },
      {
        id: 'scene_b_03_impressionism',
        number: '03',
        nameCn: '印象派与点彩',
        nameEn: 'Impressionist Oil',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_b_03_impressionism.jpg',
        hasImage: true,
        tags: ['光色颤动', '水面粼粼', '莫奈色调'],
        master: '莫奈 / 卡米耶·毕沙罗',
        colorTone: '暮光粉紫、黄绿车身与闪烁路灯',
        technique: '碎点笔触捕捉落日余晖中海滨路面的色彩颤动。',
        prompt: 'Impressionist oil painting of a coastal city intersection at twilight after rain with a vintage yellow tram, flickering unmixed brushstrokes, Claude Monet and Pissarro style, shimmering water reflections and vibrant sunset light vibration --ar 16:9',
        keyModifiers: ['Impressionist oil painting', 'flickering unmixed brushstrokes', 'Claude Monet style', 'shimmering water reflections']
      },
      {
        id: 'scene_b_04_silkscreen',
        number: '04',
        nameCn: '丝网版画 / 波普',
        nameEn: 'Silkscreen / Pop Art',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_b_04_silkscreen.jpg',
        hasImage: true,
        tags: ['亮黄电车', '平涂高反差', '版画套印'],
        master: 'Andy Warhol',
        colorTone: '明黄、品红与深紫高对比套印',
        technique: '鲜明色块与多层套印微错位，极具现代潮流海报张力。',
        prompt: 'Silkscreen screenprint artwork of a coastal street intersection with a vintage yellow tram at twilight, high contrast pop art style, bold flat color blocks, misregistration offset print effect, Andy Warhol graphic city poster --ar 16:9',
        keyModifiers: ['Silkscreen screenprint artwork', 'high contrast pop art style', 'bold flat color blocks', 'misregistration offset print']
      },
      {
        id: 'scene_b_05_ukiyoe',
        number: '05',
        nameCn: '浮世绘木刻版画',
        nameEn: 'Japanese Ukiyo-e',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_b_05_ukiyoe.jpg',
        hasImage: true,
        tags: ['广重名所绘', '雨丝墨线', '和纸青海波'],
        master: '歌川广重《名所江户百景》',
        colorTone: '普鲁士蓝波浪、墨黑轨道与黄土色电车',
        technique: '传统名所绘构图，细密斜向雨丝墨线与木刻版画拓印感。',
        prompt: 'Authentic Japanese Ukiyo-e woodblock print of a coastal city street with a vintage tram in the rain, distant sea horizon, crisp black sumi ink lines, flat mineral pigment washes, washi paper texture, Hiroshige Meisho Edo style --ar 16:9',
        keyModifiers: ['Japanese Ukiyo-e woodblock print', 'Hiroshige style', 'crisp black sumi ink lines', 'flat mineral pigment washes']
      },
      {
        id: 'scene_b_06_vintage_comic',
        number: '06',
        nameCn: '美漫复古网点',
        nameEn: 'Vintage Comic / Ben-Day Dots',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_b_06_vintage_comic.jpg',
        hasImage: true,
        tags: ['分镜线条', '四色网点', '复古街景'],
        master: 'Roy Lichtenstein',
        colorTone: '经典 CMYK 原色网点印刷',
        technique: '黄金时代漫画硬墨线与本戴圆点模拟黄昏过渡。',
        prompt: 'Vintage 1960s comic book panel of a coastal street intersection with a vintage yellow tram after rain, Roy Lichtenstein style, prominent Ben-Day halftone dots, bold black ink contour lines, CMYK 4-color printing bleed, aged pulp paper --ar 16:9',
        keyModifiers: ['Vintage 1960s comic book panel', 'Roy Lichtenstein style', 'prominent Ben-Day halftone dots', 'bold black ink contour lines']
      },
      {
        id: 'scene_b_07_citypop',
        number: '07',
        nameCn: 'City Pop 昭和复古',
        nameEn: '1980s City Pop Aesthetic',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_b_07_citypop.jpg',
        hasImage: true,
        tags: ['海滨椰树', '电车与晚霞', '永井博海风'],
        master: '永井博 (Hiroshi Nagai) / 铃木英人',
        colorTone: '钴蓝海面、粉橙晚霞与纯黄电车',
        technique: '度假海风与都市惬意感，干净利落的硬阴影与渐变晚霞。',
        prompt: '1980s Japanese City Pop aesthetic illustration by Hiroshi Nagai and Eizin Suzuki, a coastal street with a vintage yellow tram, palm trees, glowing sunset ocean horizon, pastel gradient sky, clean flat shadows, retro 80s album cover art --ar 16:9',
        keyModifiers: ['1980s Japanese City Pop aesthetic', 'Hiroshi Nagai style', 'pastel gradient sky', 'clean flat shadows', 'retro 80s album cover art']
      },
      {
        id: 'scene_b_08_artnouveau',
        number: '08',
        nameCn: '新艺术运动',
        nameEn: 'Art Nouveau Architecture',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_b_08_artnouveau.jpg',
        hasImage: true,
        tags: ['铁艺路灯曲线', '花卉装饰边框', '石版画典雅'],
        master: 'Alphonse Mucha',
        colorTone: '古铜金、橄榄绿与夕阳暖橙',
        technique: '铁艺路灯、轨道与植物花藤的有机曲线互相交织。',
        prompt: 'Art Nouveau illustration of a coastal tram street at twilight, Alphonse Mucha style, elegant sinuous flowing lines on iron lamp posts and rails, decorative botanical frame, golden sunset accents, vintage lithograph art --ar 16:9',
        keyModifiers: ['Art Nouveau illustration', 'Alphonse Mucha style', 'sinuous flowing lines', 'decorative botanical frame', 'golden sunset accents']
      },
      {
        id: 'scene_b_09_artdeco',
        number: '09',
        nameCn: '装饰风艺术',
        nameEn: 'Art Deco Urban',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_b_09_artdeco.jpg',
        hasImage: true,
        tags: ['流线型电车', '几何透视', '黑金奢华'],
        master: 'Tamara de Lempicka',
        colorTone: '曜石黑、香槟金与金属银灰',
        technique: '流线型车体与建筑强透视，展现20年代工业奢华。',
        prompt: 'Art Deco illustration of a coastal city street with a streamlined vintage yellow tram at twilight, sleek geometric architectural lines, radiant gold and navy blue palette, dramatic 1920s symmetrical perspective, Gatsby luxury --ar 16:9',
        keyModifiers: ['Art Deco illustration', 'sleek geometric architectural lines', 'radiant gold and navy blue palette', 'Gatsby luxury']
      },
      {
        id: 'scene_b_10_cyberpunk',
        number: '10',
        nameCn: '赛博朋克霓虹',
        nameEn: 'Cyberpunk Tram City',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_b_10_cyberpunk.jpg',
        hasImage: true,
        tags: ['磁悬浮列车', '霓虹招牌倒影', '雨雾光束'],
        master: 'Syd Mead / Blade Runner',
        colorTone: '青蓝 (Cyan) 与荧光洋红 (Magenta)',
        technique: '发光悬浮列车穿梭在雨雾霓虹大厦之间，水洼倒影璀璨。',
        prompt: 'Cyberpunk neon illustration of a futuristic tram crossing a rain-drenched coastal city intersection at night, vibrant glowing cyan and magenta holographic signs, steam rising, glossy wet asphalt reflections, Blade Runner aesthetic --ar 16:9',
        keyModifiers: ['Cyberpunk neon illustration', 'glowing cyan and magenta holographic signs', 'glossy wet asphalt reflections', 'Blade Runner aesthetic']
      },
      {
        id: 'scene_b_11_ghibli',
        number: '11',
        nameCn: '吉卜力 / 赛璐珞平涂',
        nameEn: 'Studio Ghibli Seaside',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_b_11_ghibli.jpg',
        hasImage: true,
        tags: ['海边小镇', '江之电感', '蓬松积雨云'],
        master: '男鹿和雄 / 宫崎骏',
        colorTone: '青绿海岛、黄色江之电与纯白积雨云',
        technique: '经典江之岛海滨手绘风光，云朵层次丰富，治愈感十足。',
        prompt: 'Anime cel-shaded landscape in the style of Studio Ghibli and Makoto Shinkai, a seaside town street with a vintage yellow tram after summer rain, fluffy sunset clouds, sparkling lens flares, Kazuo Oga painted scenery, heartwarming nostalgia --ar 16:9',
        keyModifiers: ['Anime cel-shaded landscape', 'Studio Ghibli style', 'Kazuo Oga painted scenery', 'sparkling lens flares', 'heartwarming nostalgia']
      },
      {
        id: 'scene_b_12_flatvector',
        number: '12',
        nameCn: '极简扁平矢量',
        nameEn: 'Minimalist Flat Vector',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_b_12_flatvector.jpg',
        hasImage: true,
        tags: ['纯色剪影', '极简海平线', '几何色块'],
        master: 'Malika Favre',
        colorTone: '深邃群青、亮黄与珊瑚橙',
        technique: '剔除复杂细节，用利落几何形状勾勒电车与海平线。',
        prompt: 'Minimalist flat vector graphic illustration by Malika Favre of a coastal tram intersection at sunset, bold geometric shapes, high contrast negative space, razor-sharp clean edges, chic modern travel poster --ar 16:9',
        keyModifiers: ['Minimalist flat vector graphic illustration', 'Malika Favre style', 'bold geometric shapes', 'high contrast negative space', 'razor-sharp clean edges']
      },
      {
        id: 'scene_b_13_pixelart',
        number: '13',
        nameCn: '16-bit 像素风',
        nameEn: '16-bit Pixel Seaside',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_b_13_pixelart.jpg',
        hasImage: true,
        tags: ['点阵水洼', '街机横版', '像素落日'],
        master: 'SNES 街机大作',
        colorTone: '16色经典街机调色板',
        technique: '横版卷轴游戏视角，点阵水洼倒影与晚霞渐变网点。',
        prompt: '16-bit pixel art of a coastal city street intersection at twilight after rain, a vintage yellow tram passing, glowing streetlights reflected in puddles, meticulous pixel dithering, nostalgic retro 90s arcade aesthetic --ar 16:9',
        keyModifiers: ['16-bit pixel art', 'meticulous pixel dithering', 'glowing streetlights reflected in puddles', 'retro 90s arcade aesthetic']
      },
      {
        id: 'scene_b_14_crayon',
        number: '14',
        nameCn: '绘本蜡笔与拼贴',
        nameEn: 'Picture Book Story',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_b_14_crayon.jpg',
        hasImage: true,
        tags: ['童趣小镇', '蜡笔手感', '剪纸层次'],
        master: 'Eric Carle',
        colorTone: '暖黄、草绿与质朴赭石',
        technique: '撕纸贴画与粗颗粒油画棒涂抹，营造童话绘本故事感。',
        prompt: 'Whimsical children\'s picture book illustration of a cute yellow tram driving through a rainy coastal town at dusk, visible waxy crayon textures, soft oil pastels, torn paper collage elements, warm cozy storybook art --ar 16:9',
        keyModifiers: ['children\'s picture book illustration', 'visible waxy crayon textures', 'soft oil pastels', 'torn paper collage elements']
      }
    ]
  },
  {
    id: 'scene_c',
    title: '场景 C · 悬崖古树与镜湖',
    subtitle: '自然与宏大风光 · 材质与写意度测试',
    badge: '16:9 全景比例',
    description: '悬崖边缘盛开的孤树，俯瞰宁静镜面湖泊，远方雪山与晚霞落日。用于测试自然笔触、色彩渐变、水体质感、空气透视与写意度。',
    coreSubject: 'A solitary ancient blossoming cherry tree standing on a rocky cliff overlooking a serene alpine lake at sunset, distant snowy mountain peaks, dramatic clouds',
    aspectRatio: '16:9',
    styles: [
      {
        id: 'scene_c_01_impasto',
        number: '01',
        nameCn: '厚涂油画',
        nameEn: 'Impasto Oil Painting',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_c_01_impasto.jpg',
        hasImage: true,
        tags: ['粗粝岩石', '雕塑般花瓣', '暮光浓厚'],
        master: 'Craig Mullins / 梵高',
        colorTone: '暖金、赭石与普鲁士蓝山体',
        technique: '粗粝厚重的刮刀堆叠岩石与繁密花簇。',
        prompt: 'Impasto oil painting of a solitary blossoming cherry tree on a rocky cliff overlooking a serene alpine lake at sunset, distant snowy peaks, thick sculptural palette knife strokes, heavy oil paint texture, dramatic rich golden-hour lighting --ar 16:9',
        keyModifiers: ['Impasto oil painting', 'thick sculptural palette knife strokes', 'heavy oil paint texture', 'golden-hour lighting']
      },
      {
        id: 'scene_c_02_watercolor',
        number: '02',
        nameCn: '通透水彩',
        nameEn: 'Luminous Watercolor',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_c_02_watercolor.jpg',
        hasImage: true,
        tags: ['湖光山色', '空灵浸染', '留白诗意'],
        master: '吴冠中 / 现代水彩',
        colorTone: '淡粉樱花、水绿湖泊与冷灰远山',
        technique: '大面积湿画法晕染湖面与远方雪山，花瓣点缀其上。',
        prompt: 'Luminous watercolor landscape of an ancient blossoming tree on a cliff overlooking a calm alpine lake at sunset, distant mountains, translucent wet-on-wet bleeding washes, soft gradient skies, visible cold-press paper grain, delicate ink accents --ar 16:9',
        keyModifiers: ['Luminous watercolor landscape', 'translucent wet-on-wet bleeding washes', 'soft gradient skies', 'visible cold-press paper grain']
      },
      {
        id: 'scene_c_03_impressionism',
        number: '03',
        nameCn: '印象派与点彩',
        nameEn: 'Impressionist Landscape',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_c_03_impressionism.jpg',
        hasImage: true,
        tags: ['波光粼粼', '莫奈粉紫', '空气颤动'],
        master: 'Claude Monet',
        colorTone: '粉紫晚霞、金橙倒影与群青水面',
        technique: '点状纯色笔触捕捉水面落日反光与空气颤动感。',
        prompt: 'Impressionist oil painting of a blossoming tree on a cliff overlooking a serene lake at sunset, loose dappled brushstrokes, Claude Monet style, vibrant flickering color spots, shimmering water surface, atmospheric light vibration --ar 16:9',
        keyModifiers: ['Impressionist oil painting', 'loose dappled brushstrokes', 'Claude Monet style', 'vibrant flickering color spots', 'shimmering water surface']
      },
      {
        id: 'scene_c_04_silkscreen',
        number: '04',
        nameCn: '丝网版画 / 波普',
        nameEn: 'Silkscreen Landscape',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_c_04_silkscreen.jpg',
        hasImage: true,
        tags: ['明丽色块', '自然版画', '套印美学'],
        master: 'Andy Warhol',
        colorTone: '荧光粉樱花、明黄天空与翠绿山体',
        technique: '波普艺术色彩分离与丝网多色套印。',
        prompt: 'Silkscreen screenprint artwork of a blossoming tree on a cliff overlooking a lake and distant mountains, bold flat color blocks, slight misregistration print offset, high contrast pop art style, Andy Warhol nature poster --ar 16:9',
        keyModifiers: ['Silkscreen screenprint artwork', 'bold flat color blocks', 'slight misregistration print offset', 'Andy Warhol nature poster']
      },
      {
        id: 'scene_c_05_ukiyoe',
        number: '05',
        nameCn: '浮世绘木刻版画',
        nameEn: 'Ukiyo-e Mount Fuji',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_c_05_ukiyoe.jpg',
        hasImage: true,
        tags: ['北斋樱花', '水墨山形', '和纸拓印'],
        master: '葛饰北斋《富岳三十六景》',
        colorTone: '富士山白雪、深黛青山脚与樱粉',
        technique: '经典的富士山远眺构图，前景樱花墨线勾勒，和纸肌理。',
        prompt: 'Authentic Japanese Ukiyo-e woodblock print of an ancient sakura tree on a cliff overlooking Mount Fuji and a calm lake at sunset, crisp black sumi-e outlines, flat mineral pigment washes, washi paper texture, Hokusai style --ar 16:9',
        keyModifiers: ['Japanese Ukiyo-e woodblock print', 'Hokusai style', 'crisp black sumi-e outlines', 'flat mineral pigment washes', 'washi paper texture']
      },
      {
        id: 'scene_c_06_vintage_comic',
        number: '06',
        nameCn: '美漫复古网点',
        nameEn: 'Vintage Comic Nature',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_c_06_vintage_comic.jpg',
        hasImage: true,
        tags: ['硬朗黑线', '网点晚霞', '复古科幻感'],
        master: 'Roy Lichtenstein',
        colorTone: '粗黑线条与四色网点渐变',
        technique: '美漫分镜构图，网点表现山体与湖水渐变。',
        prompt: 'Vintage 1960s comic book illustration of a blossoming tree on a cliff overlooking a mountain lake at sunset, Roy Lichtenstein style, prominent Ben-Day halftone dots, bold black ink contour lines, aged pulp paper texture --ar 16:9',
        keyModifiers: ['Vintage 1960s comic book illustration', 'Roy Lichtenstein style', 'prominent Ben-Day halftone dots', 'bold black ink contour lines']
      },
      {
        id: 'scene_c_07_citypop',
        number: '07',
        nameCn: 'City Pop 昭和复古',
        nameEn: 'City Pop Resort Nature',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_c_07_citypop.jpg',
        hasImage: true,
        tags: ['清透蓝粉', '度假湖泊', '永井博纯净'],
        master: 'Hiroshi Nagai',
        colorTone: '纯净天蓝、粉紫晚霞与明亮反光',
        technique: '永井博经典的度假风构图，宁静纯粹的色块搭配。',
        prompt: '1980s Japanese City Pop aesthetic illustration by Hiroshi Nagai, an ancient blooming tree on a cliff overlooking a crystal clear lake at sunset, distant purple mountains, pastel sky gradients, clean flat shadows, retro 80s resort vibe --ar 16:9',
        keyModifiers: ['1980s Japanese City Pop aesthetic', 'Hiroshi Nagai style', 'pastel sky gradients', 'clean flat shadows', 'retro 80s resort vibe']
      },
      {
        id: 'scene_c_08_artnouveau',
        number: '08',
        nameCn: '新艺术运动',
        nameEn: 'Art Nouveau Botanical',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_c_08_artnouveau.jpg',
        hasImage: true,
        tags: ['蜿蜒枝丫', '植物对称框', '金箔点缀'],
        master: 'Alphonse Mucha',
        colorTone: '香槟金、孔雀绿与古典象牙白',
        technique: '树枝自然延伸成优雅的装饰曲线，外围环绕金箔边框。',
        prompt: 'Art Nouveau landscape illustration of an ancient blossoming tree on a cliff over a lake at dusk, Alphonse Mucha style, sinuous organic floral branches, intricate decorative circular botanical frame, golden leaf accents, elegant lithograph --ar 16:9',
        keyModifiers: ['Art Nouveau landscape illustration', 'Alphonse Mucha style', 'sinuous organic floral branches', 'decorative circular botanical frame', 'golden leaf accents']
      },
      {
        id: 'scene_c_09_artdeco',
        number: '09',
        nameCn: '装饰风艺术',
        nameEn: 'Art Deco Grandeur',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_c_09_artdeco.jpg',
        hasImage: true,
        tags: ['几何太阳芒', '对称山体', '金绿奢华'],
        master: 'Tamara de Lempicka',
        colorTone: '曜石黑、翠绿与放射金芒',
        technique: '放射状对称的几何落日光芒与棱角分明的山峦。',
        prompt: 'Art Deco illustration of an ancient tree on a cliff overlooking a mountain lake at sunset, sleek geometric stylized branches, radiating gold and teal sunbeams, glamorous symmetrical 1920s Gatsby aesthetic --ar 16:9',
        keyModifiers: ['Art Deco illustration', 'sleek geometric stylized branches', 'radiating gold and teal sunbeams', 'Gatsby aesthetic']
      },
      {
        id: 'scene_c_10_cyberpunk',
        number: '10',
        nameCn: '赛博朋克全息',
        nameEn: 'Cyberpunk Holographic',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_c_10_cyberpunk.jpg',
        hasImage: true,
        tags: ['全息发光樱花', '远景赛博巨构', '电光湖面倒影'],
        master: 'Blade Runner / 未来概念设计',
        colorTone: '荧光青、品红激光与深黑夜幕',
        technique: '悬崖上的全息数码樱花树在暗夜中发光，湖面反射激光网格。',
        prompt: 'Cyberpunk sci-fi landscape of a glowing holographic sakura tree on a cliff overlooking a dark reflective lake, distant neon megacity spires under night sky, vivid cyan and magenta laser light, volumetric mist, Blade Runner vibe --ar 16:9',
        keyModifiers: ['Cyberpunk sci-fi landscape', 'glowing holographic sakura tree', 'neon megacity spires', 'vivid cyan and magenta laser light', 'Blade Runner vibe']
      },
      {
        id: 'scene_c_11_ghibli',
        number: '11',
        nameCn: '吉卜力 / 赛璐珞平涂',
        nameEn: 'Studio Ghibli Epic Vista',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_c_11_ghibli.jpg',
        hasImage: true,
        tags: ['男鹿和雄画风', '宏大云海', '治愈风光'],
        master: '男鹿和雄 / 宫崎骏',
        colorTone: '青翠草甸、澄澈湖蓝与壮丽晚霞',
        technique: '男鹿和雄式细腻水粉手绘大自然，壮阔而治愈。',
        prompt: 'Anime cel-shaded landscape in the style of Studio Ghibli, a giant blossoming cherry tree on a cliff overlooking a calm blue lake, distant snow mountains, massive fluffy sunset clouds, hand-painted Kazuo Oga background, heartwarming and breathtaking --ar 16:9',
        keyModifiers: ['Anime cel-shaded landscape', 'Studio Ghibli style', 'Kazuo Oga background', 'massive fluffy sunset clouds', 'heartwarming and breathtaking']
      },
      {
        id: 'scene_c_12_flatvector',
        number: '12',
        nameCn: '极简扁平矢量',
        nameEn: 'Minimalist Vector Mountain',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_c_12_flatvector.jpg',
        hasImage: true,
        tags: ['孤树剪影', '高反差负空间', '现代旅行海报'],
        master: 'Malika Favre',
        colorTone: '纯黑剪影、明橙落日与深蓝湖泊',
        technique: '极简矢量剪影构图，强烈的负空间现代艺术感。',
        prompt: 'Minimalist flat vector graphic illustration by Malika Favre, a silhouette of a solitary tree on a cliff over a calm lake at sunset, bold geometric color blocking, high contrast negative space, clean razor-sharp vector lines --ar 16:9',
        keyModifiers: ['Minimalist flat vector graphic illustration', 'Malika Favre style', 'bold geometric color blocking', 'high contrast negative space', 'razor-sharp vector lines']
      },
      {
        id: 'scene_c_13_pixelart',
        number: '13',
        nameCn: '16-bit 像素风',
        nameEn: '16-bit Pixel Landscape',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_c_13_pixelart.jpg',
        hasImage: true,
        tags: ['RPG大地图', '点阵雪山', '像素晚霞渐变'],
        master: 'SFC / 八方旅人风格',
        colorTone: '经典 16-bit 怀旧色盘',
        technique: '复古日系 RPG 史诗大地图风光，精细的像素抖动过渡。',
        prompt: '16-bit pixel art of an ancient blossoming tree on a cliff overlooking a calm alpine lake at sunset, distant snowy mountain peaks, glowing sky gradients, meticulous pixel dithering, nostalgic retro 90s RPG game vista --ar 16:9',
        keyModifiers: ['16-bit pixel art', 'meticulous pixel dithering', 'retro 90s RPG game vista', 'glowing sky gradients']
      },
      {
        id: 'scene_c_14_crayon',
        number: '14',
        nameCn: '绘本蜡笔与拼贴',
        nameEn: 'Picture Book Nature',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_c_14_crayon.jpg',
        hasImage: true,
        tags: ['童趣大树', '蜡笔波光', '剪贴自然'],
        master: 'Eric Carle',
        colorTone: '温暖草木绿、金黄与天真粉红',
        technique: '手工水彩刮色纸剪贴与蜡笔线条，充满生机与童真。',
        prompt: 'Whimsical children\'s picture book illustration of a giant blossoming tree on a cliff overlooking a quiet lake and mountains, visible waxy crayon strokes, soft oil pastel texture, layered collage paper cutouts, Eric Carle style --ar 16:9',
        keyModifiers: ['children\'s picture book illustration', 'visible waxy crayon strokes', 'soft oil pastel texture', 'layered collage paper cutouts', 'Eric Carle style']
      }
    ]
  }
];
