/**
 * 艺术风格矩阵数据集 (Art Style Matrix Database)
 * 涵盖 3 大基准测试场景 × 14 种经典艺术与插画流派 (全 42 组完整出图与视觉图谱)
 */

const STYLE_CATEGORIES = [
  { id: 'all', name: '全部流派', icon: 'layout-grid', desc: '全量 14 种经典绘画与插画流派' },
  { id: 'fine_art', name: '传统绘画与油彩', icon: 'palette', desc: '颜料堆叠、笔触肌理与古典光影层次' },
  { id: 'printmaking', name: '版画与印刷媒介', icon: 'printer', desc: '套印对位、网点纹理与木刻矿物拓印' },
  { id: 'retro_pop', name: '时代美学与潮流', icon: 'compass', desc: '经典时代符号、装饰曲线与复古光泽' },
  { id: 'digital', name: '现代数码与概念', icon: 'monitor', desc: '极简矢量、赛璐珞光影与点阵像素美学' }
];

const SCENES_DATA = [
  {
    id: 'scene_a',
    title: 'I · 咖啡馆雨窗与猫',
    subtitle: '人物肖像 · 室内外冷暖光影与织物质感',
    badge: '3:4 肖像比例',
    description: '咖啡馆雨窗旁，戴宽檐帽喝咖啡的优雅女性，木桌上趴着一只睡猫。用于测试人物五官结构、衣褶质感、室内外冷暖对比与情绪传达。',
    coreSubject: 'A stylish woman in a wide-brim hat sitting by a rainy cafe window, sipping coffee, a fluffy cat sleeping on the wooden table',
    aspectRatio: '3:4',
    styles: [
      {
        id: 'scene_a_01_impasto',
        number: '01',
        nameCn: '厚涂油画',
        nameEn: 'Impasto Oil Painting',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_a_01_impasto.jpg',
        hasImage: true,
        tags: ['颜料堆叠', '油画刀刮痕', '明暗对比', '厚重体积'],
        master: 'Craig Mullins / 梵高 / 伦勃朗',
        colorTone: '浓郁赭石、普鲁士蓝与暖灯金光',
        technique: '使用厚重油彩与油画刀层叠涂抹，强调厚重物理肌理与雕塑般的形体转折。',
        prompt: 'Impasto oil painting of a stylish woman in a wide-brim hat sitting by a rainy cafe window, sipping coffee, a fluffy cat sleeping on the wooden table, thick visible palette knife strokes, heavy textured oil paint, rich chiaroscuro lighting, Craig Mullins style --ar 3:4',
        keyModifiers: ['impasto oil painting', 'thick visible palette knife strokes', 'heavy textured oil paint', 'rich chiaroscuro lighting', 'Craig Mullins style']
      },
      {
        id: 'scene_a_02_watercolor',
        number: '02',
        nameCn: '通透水彩',
        nameEn: 'Luminous Watercolor',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_a_02_watercolor.jpg',
        hasImage: true,
        tags: ['湿画晕染', '边缘渗色', '水光透明', '冷压纸纹'],
        master: 'Sargent / 现代水彩插画',
        colorTone: '焦茶色毛衣、水色蓝灰与暖橙街灯',
        technique: '利用水分在粗纹水彩纸上的自然扩散与留白，形成半透明的色彩交融与雨水流动感。',
        prompt: 'Luminous watercolor painting of a stylish woman in a wide-brim hat sitting by a rainy cafe window, sipping coffee, a fluffy cat sleeping on the wooden table, wet-on-wet bleeding washes, translucent watercolor pigments, visible cold-press paper grain, delicate soft ink lines --ar 3:4',
        keyModifiers: ['luminous watercolor painting', 'wet-on-wet bleeding washes', 'translucent watercolor pigments', 'visible cold-press paper grain', 'delicate soft ink lines']
      },
      {
        id: 'scene_a_03_impressionism',
        number: '03',
        nameCn: '印象派与点彩',
        nameEn: 'Impressionist Oil',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_a_03_impressionism.jpg',
        hasImage: true,
        tags: ['瞬时光影', '颤动笔触', '色彩并置', '空气透视'],
        master: '莫奈 (Monet) / 皮萨罗 (Pissarro)',
        colorTone: '钴蓝大衣、草编草帽金黄与暖色室内灯火',
        technique: '以碎小跳跃的纯色笔触并置，利用人眼视觉混合产生光彩闪烁的颤动感。',
        prompt: 'Impressionist oil painting of a stylish woman in a wide-brim hat sitting by a rainy cafe window, sipping coffee, a fluffy cat sleeping on the wooden table, loose flickering brushstrokes, Claude Monet style, vibrant unmixed color vibration, dappled ambient light --ar 3:4',
        keyModifiers: ['impressionist oil painting', 'loose flickering brushstrokes', 'Claude Monet style', 'vibrant unmixed color vibration', 'dappled ambient light']
      },
      {
        id: 'scene_a_04_silkscreen',
        number: '04',
        nameCn: '丝网版画 / 波普艺术',
        nameEn: 'Silkscreen / Pop Art',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_a_04_silkscreen.jpg',
        hasImage: true,
        tags: ['对位错版', '高饱和平涂', '粗颗粒网点', '波普海报'],
        master: '安迪·沃霍尔 (Andy Warhol)',
        colorTone: '青蓝、明黄与荧光洋红的剧烈对撞',
        technique: '模拟手工丝网多层孔版套印，带有标志性的边缘微错位与印刷漏色质感。',
        prompt: 'Silkscreen screenprint pop art of a stylish woman in a wide-brim hat sitting by a rainy cafe window, sipping coffee, a fluffy cat sleeping on the wooden table, bold flat color blocks, slight misregistration print offset, Andy Warhol graphic poster aesthetic --ar 3:4',
        keyModifiers: ['silkscreen screenprint pop art', 'bold flat color blocks', 'slight misregistration print offset', 'Andy Warhol graphic poster aesthetic']
      },
      {
        id: 'scene_a_05_ukiyoe',
        number: '05',
        nameCn: '浮世绘木刻版画',
        nameEn: 'Japanese Ukiyo-e',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_a_05_ukiyoe.jpg',
        hasImage: true,
        tags: ['黑墨勾线', '矿物颜料平涂', '和纸纤维', '散点构图'],
        master: '葛饰北斋 / 歌川广重',
        colorTone: '深青花和服、浅土黄木构与和纸米白',
        technique: '严谨克制的木刻雕版墨线，搭配传统矿物植物颜料的大面积平涂与木质拓印感。',
        prompt: 'Authentic Japanese Ukiyo-e woodblock print of a stylish woman in a wide-brim hat sitting by a rainy cafe window, sipping coffee, a sleeping cat on the wooden table, crisp black sumi-e outlines, flat mineral pigment washes, washi paper texture, Hokusai style --ar 3:4',
        keyModifiers: ['Japanese Ukiyo-e woodblock print', 'crisp black sumi-e outlines', 'flat mineral pigment washes', 'washi paper texture', 'Hokusai style']
      },
      {
        id: 'scene_a_06_vintage_comic',
        number: '06',
        nameCn: '美漫复古网点',
        nameEn: 'Vintage Comic / Ben-Day Dots',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_a_06_vintage_comic.jpg',
        hasImage: true,
        tags: ['本戴网点', '四色套印', '墨线硬边', '漫画对话框'],
        master: '罗伊·利希滕斯坦 (Roy Lichtenstein)',
        colorTone: 'CMYK 原色体系（纯黄、纯红、深黑与网点青）',
        technique: '20世纪60年代美漫低成本印刷工艺，利用密集的原色小圆点并置形成灰阶与阴影。',
        prompt: 'Vintage 1960s comic book illustration of a stylish woman in a wide-brim hat sitting by a rainy cafe window, sipping coffee, a cat sleeping on the table, Roy Lichtenstein style, prominent Ben-Day halftone dots, bold black ink contour lines, aged pulp paper texture --ar 3:4',
        keyModifiers: ['vintage 1960s comic book illustration', 'Roy Lichtenstein style', 'prominent Ben-Day halftone dots', 'bold black ink contour lines', 'aged pulp paper texture']
      },
      {
        id: 'scene_a_07_citypop',
        number: '07',
        nameCn: 'City Pop 昭和复古',
        nameEn: '1980s City Pop Aesthetic',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_a_07_citypop.jpg',
        hasImage: true,
        tags: ['粉紫晚霞', '几何硬影', '霓虹招牌', '都市假日感'],
        master: '永井博 (Hiroshi Nagai) / 铃木英人',
        colorTone: '海蓝、粉紫渐变晚霞、鹅黄与翠绿',
        technique: '80年代日本黑胶唱片封套美学，干净明快的色块过渡，几何化的扁平硬阴影与复古度假氛围。',
        prompt: '1980s Japanese City Pop aesthetic illustration by Hiroshi Nagai and Eizin Suzuki, a stylish woman in a wide-brim hat sitting by a cafe window, sipping coffee, a cat sleeping on the table, vibrant pastel sky gradients, clean flat shadows, retro 80s album cover vibe --ar 3:4',
        keyModifiers: ['1980s Japanese City Pop aesthetic', 'Hiroshi Nagai style', 'Eizin Suzuki style', 'vibrant pastel sky gradients', 'clean flat shadows']
      },
      {
        id: 'scene_a_08_artnouveau',
        number: '08',
        nameCn: '新艺术运动',
        nameEn: 'Art Nouveau Masterpiece',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_a_08_artnouveau.jpg',
        hasImage: true,
        tags: ['自然藤蔓线', '植物花卉边框', '金箔装饰', '石版画优雅'],
        master: '阿尔丰斯·慕夏 (Alphonse Mucha)',
        colorTone: '复古烫金、橄榄绿、鸢尾紫与象牙白',
        technique: '19世纪末世纪之交的有机曲线美学，将女性柔美卷发、植物花藤与华丽的对称装饰框融为一体。',
        prompt: 'Art Nouveau masterpiece illustration of a stylish woman in a wide-brim hat sitting by a cafe window, sipping coffee, a sleeping cat, Alphonse Mucha style, flowing sinuous organic lines, intricate floral decorative borders, golden foil accents, elegant lithograph --ar 3:4',
        keyModifiers: ['Art Nouveau masterpiece illustration', 'Alphonse Mucha style', 'flowing sinuous organic lines', 'intricate floral decorative borders', 'golden foil accents']
      },
      {
        id: 'scene_a_09_artdeco',
        number: '09',
        nameCn: '装饰风艺术',
        nameEn: 'Art Deco Luxury',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_a_09_artdeco.jpg',
        hasImage: true,
        tags: ['机械几何', '放射状对称', '黑金奢华', '流线型轮廓'],
        master: '塔玛拉·德·蓝披卡 (Tamara de Lempicka)',
        colorTone: '曜石黑、香槟金、黄铜与深宝蓝',
        technique: '1920年代盖茨比时期的现代工业奢华，以折线、弧线、几何硬切面与金属光泽构建锐利的高级感。',
        prompt: 'Art Deco illustration of a glamorous woman in a wide-brim hat sitting by a rainy cafe window, sipping coffee, a sleeping cat, sleek geometric symmetry, sharp streamlined shapes, luxurious gold and obsidian palette, Tamara de Lempicka 1920s aesthetic --ar 3:4',
        keyModifiers: ['Art Deco illustration', 'sleek geometric symmetry', 'sharp streamlined shapes', 'luxurious gold and obsidian palette', 'Tamara de Lempicka 1920s aesthetic']
      },
      {
        id: 'scene_a_10_cyberpunk',
        number: '10',
        nameCn: '赛博朋克霓虹',
        nameEn: 'Cyberpunk Neon',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_a_10_cyberpunk.jpg',
        hasImage: true,
        tags: ['全息霓虹', '雨雾光晕', '机械改造猫', '高科技低生活'],
        master: '《银翼杀手》 / Syd Mead',
        colorTone: '电光青 (Cyan)、荧光洋红 (Magenta) 与深黑',
        technique: '高对比度的自发光体与湿漉沥青的反光交织，冷调雨夜与暖调全息看板的极度反差。',
        prompt: 'Cyberpunk neon illustration of a woman in a wide-brim hat sitting by a rain-streaked cafe window overlooking a futuristic neon megacity, glowing cyan and magenta reflections, steaming coffee, a cybernetic cat on the table, volumetric rain haze, Blade Runner style --ar 3:4',
        keyModifiers: ['Cyberpunk neon illustration', 'glowing cyan and magenta reflections', 'cybernetic cat', 'volumetric rain haze', 'Blade Runner style']
      },
      {
        id: 'scene_a_11_ghibli',
        number: '11',
        nameCn: '吉卜力 / 赛璐珞平涂',
        nameEn: 'Studio Ghibli / Cel Anime',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_a_11_ghibli.jpg',
        hasImage: true,
        tags: ['手绘水粉背景', '清晰硬阴影', '温馨治愈', '日系暖调'],
        master: '男鹿和雄 (Kazuo Oga) / 宫崎骏',
        colorTone: '原木暖褐、米白针织毛衣与三花猫暖色',
        technique: '经典动画手绘工序：前景人物采用干净利落的赛璐珞硬阴影，背景采用细腻写实的水粉风景画。',
        prompt: 'Anime cel-shaded illustration in the style of Studio Ghibli, a cozy woman in a hat sitting by a rain-streaked cafe window, sipping coffee, a sleeping cat on the table, hand-painted Kazuo Oga background, clean cel shadows, warm and nostalgic atmosphere --ar 3:4',
        keyModifiers: ['Anime cel-shaded illustration', 'Studio Ghibli style', 'hand-painted Kazuo Oga background', 'clean cel shadows', 'warm and nostalgic']
      },
      {
        id: 'scene_a_12_flatvector',
        number: '12',
        nameCn: '极简扁平矢量',
        nameEn: 'Minimalist Flat Vector',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_a_12_flatvector.jpg',
        hasImage: true,
        tags: ['负空间构图', '纯粹色块', '无渐变硬边', '时尚杂志海报'],
        master: 'Malika Favre',
        colorTone: '克莱因蓝、暖焦糖色、纯白与深黑',
        technique: '极度克制的视觉语言，摒弃所有噪点与过渡，用极致精准的几何形体和巧妙的负空间构建张力。',
        prompt: 'Minimalist flat vector graphic illustration by Malika Favre, a woman in a wide-brim hat sitting by a cafe window with a cup of coffee and a cat, bold geometric color blocks, brilliant negative space design, razor-sharp clean edges, high-fashion poster --ar 3:4',
        keyModifiers: ['Minimalist flat vector graphic illustration', 'Malika Favre style', 'bold geometric color blocks', 'brilliant negative space design', 'razor-sharp clean edges']
      },
      {
        id: 'scene_a_13_pixelart',
        number: '13',
        nameCn: '16-bit 像素风',
        nameEn: '16-bit Pixel Art',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_a_13_pixelart.jpg',
        hasImage: true,
        tags: ['点阵颗粒', '抖动渐变 (Dithering)', '复古UI面板', '街机复古'],
        master: 'SNES 黄金时代像素大师',
        colorTone: '红砖暖褐、钨丝灯暖黄与雨巷青蓝',
        technique: '基于严谨像素网格的手工点阵绘制，利用 Dithering（网点交错）模拟光线过渡，附带经典游戏 HUD 计分板。',
        prompt: '16-bit pixel art of a cozy woman in a hat sitting by a rainy cafe window drinking coffee, a fluffy cat sleeping on the wooden table, warm glowing indoor lights, meticulous pixel dithering, nostalgic retro 90s SNES video game aesthetic --ar 3:4',
        keyModifiers: ['16-bit pixel art', 'meticulous pixel dithering', 'retro 90s SNES video game aesthetic', 'warm glowing indoor lights']
      },
      {
        id: 'scene_a_14_crayon',
        number: '14',
        nameCn: '绘本蜡笔与拼贴',
        nameEn: 'Picture Book / Crayon Collage',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_a_14_crayon.jpg',
        hasImage: true,
        tags: ['蜡笔笔触', '油画棒颗粒', '手撕纸拼贴', '童趣质朴'],
        master: 'Eric Carle / Oliver Jeffers',
        colorTone: '暖土黄、草木绿与柔和粉蜡',
        technique: '模拟儿童绘本的手工质感，凹凸不平的蜡质肌理与剪纸边缘，散发纯真与治愈感。',
        prompt: 'Whimsical children\'s picture book illustration of a gentle woman in a wide-brim hat at a rainy cafe window with a sleeping cat and coffee, visible waxy crayon strokes, soft oil pastel texture, torn paper collage layers, Eric Carle and Oliver Jeffers style --ar 3:4',
        keyModifiers: ['children\'s picture book illustration', 'visible waxy crayon strokes', 'soft oil pastel texture', 'torn paper collage layers', 'Eric Carle style']
      }
    ]
  },
  {
    id: 'scene_b',
    title: 'II · 雨后黄昏海滨电车',
    subtitle: '街景建筑 · 空间透视与水洼倒影',
    badge: '16:9 全景比例',
    description: '雨后黄昏的海滨街口，一辆复古黄色有轨电车驶过，路面水洼倒影与路灯。用于测试透视线条、建筑几何、反光倒影、冷暖色彩与时代感。',
    coreSubject: 'A coastal city street intersection at twilight after rain, a vintage yellow tram passing on rails, glowing street lamps, wet reflections on asphalt, ocean horizon',
    aspectRatio: '16:9',
    styles: [
      {
        id: 'scene_b_01_impasto',
        number: '01',
        nameCn: '厚涂油画',
        nameEn: 'Impasto Oil Painting',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_b_01_impasto.jpg',
        hasImage: true,
        tags: ['厚重刮刀', '湿路反光', '暮色苍茫'],
        master: 'Craig Mullins / 伦勃朗',
        colorTone: '深焦糖、赭石与街灯金光',
        technique: '厚重刮刀堆叠沥青路面水光反光，富有雕塑感。',
        prompt: 'Impasto oil painting of a coastal city street intersection at twilight after rain, a vintage yellow tram on rails, glowing street lamps, wet reflections on asphalt, thick expressive palette knife strokes, heavy oil texture, rich dramatic evening light --ar 16:9',
        keyModifiers: ['Impasto oil painting', 'thick expressive palette knife strokes', 'heavy oil texture', 'rich dramatic evening light']
      },
      {
        id: 'scene_b_02_watercolor',
        number: '02',
        nameCn: '通透水彩',
        nameEn: 'Luminous Watercolor',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_b_02_watercolor.jpg',
        hasImage: true,
        tags: ['湿画水滩', '光晕弥散', '轻灵通透'],
        master: 'Alvaro Castagnet / 现代水彩',
        colorTone: '水色青蓝、路面湿润倒影与柔和光晕',
        technique: '湿画法表现地面积水漫反射与海风吹拂的朦胧感。',
        prompt: 'Luminous watercolor painting of a coastal city street intersection at twilight after rain, a vintage yellow tram passing, glowing street lamps, wet-on-wet bleeding washes, delicate puddles with soft reflections, visible cold-press paper grain, poetic and breezy --ar 16:9',
        keyModifiers: ['Luminous watercolor painting', 'wet-on-wet bleeding washes', 'delicate puddles with soft reflections', 'visible cold-press paper grain']
      },
      {
        id: 'scene_b_03_impressionism',
        number: '03',
        nameCn: '印象派与点彩',
        nameEn: 'Impressionist Oil',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_b_03_impressionism.jpg',
        hasImage: true,
        tags: ['光色颤动', '水面粼粼', '莫奈色调'],
        master: '莫奈 / 卡米耶·毕沙罗',
        colorTone: '暮光粉紫、黄绿车身与闪烁路灯',
        technique: '碎点笔触捕捉落日余晖中海滨路面的色彩颤动。',
        prompt: 'Impressionist oil painting of a coastal city intersection at twilight after rain with a vintage yellow tram, flickering unmixed brushstrokes, Claude Monet and Pissarro style, shimmering water reflections and vibrant sunset light vibration --ar 16:9',
        keyModifiers: ['Impressionist oil painting', 'flickering unmixed brushstrokes', 'Claude Monet style', 'shimmering water reflections']
      },
      {
        id: 'scene_b_04_silkscreen',
        number: '04',
        nameCn: '丝网版画 / 波普',
        nameEn: 'Silkscreen / Pop Art',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_b_04_silkscreen.jpg',
        hasImage: true,
        tags: ['亮黄电车', '平涂高反差', '版画套印'],
        master: 'Andy Warhol',
        colorTone: '明黄、品红与深紫高对比套印',
        technique: '鲜明色块与多层套印微错位，极具现代潮流海报张力。',
        prompt: 'Silkscreen screenprint artwork of a coastal street intersection with a vintage yellow tram at twilight, high contrast pop art style, bold flat color blocks, misregistration offset print effect, Andy Warhol graphic city poster --ar 16:9',
        keyModifiers: ['Silkscreen screenprint artwork', 'high contrast pop art style', 'bold flat color blocks', 'misregistration offset print']
      },
      {
        id: 'scene_b_05_ukiyoe',
        number: '05',
        nameCn: '浮世绘木刻版画',
        nameEn: 'Japanese Ukiyo-e',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_b_05_ukiyoe.jpg',
        hasImage: true,
        tags: ['广重名所绘', '雨丝墨线', '和纸青海波'],
        master: '歌川广重《名所江户百景》',
        colorTone: '普鲁士蓝波浪、墨黑轨道与黄土色电车',
        technique: '传统名所绘构图，细密斜向雨丝墨线与木刻版画拓印感。',
        prompt: 'Authentic Japanese Ukiyo-e woodblock print of a coastal city street with a vintage tram in the rain, distant sea horizon, crisp black sumi ink lines, flat mineral pigment washes, washi paper texture, Hiroshige Meisho Edo style --ar 16:9',
        keyModifiers: ['Japanese Ukiyo-e woodblock print', 'Hiroshige style', 'crisp black sumi ink lines', 'flat mineral pigment washes']
      },
      {
        id: 'scene_b_06_vintage_comic',
        number: '06',
        nameCn: '美漫复古网点',
        nameEn: 'Vintage Comic / Ben-Day Dots',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_b_06_vintage_comic.jpg',
        hasImage: true,
        tags: ['分镜线条', '四色网点', '复古街景'],
        master: 'Roy Lichtenstein',
        colorTone: '经典 CMYK 原色网点印刷',
        technique: '黄金时代漫画硬墨线与本戴圆点模拟黄昏过渡。',
        prompt: 'Vintage 1960s comic book panel of a coastal street intersection with a vintage yellow tram after rain, Roy Lichtenstein style, prominent Ben-Day halftone dots, bold black ink contour lines, CMYK 4-color printing bleed, aged pulp paper --ar 16:9',
        keyModifiers: ['Vintage 1960s comic book panel', 'Roy Lichtenstein style', 'prominent Ben-Day halftone dots', 'bold black ink contour lines']
      },
      {
        id: 'scene_b_07_citypop',
        number: '07',
        nameCn: 'City Pop 昭和复古',
        nameEn: '1980s City Pop Aesthetic',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_b_07_citypop.jpg',
        hasImage: true,
        tags: ['海滨椰树', '电车与晚霞', '永井博海风'],
        master: '永井博 (Hiroshi Nagai) / 铃木英人',
        colorTone: '钴蓝海面、粉橙晚霞与纯黄电车',
        technique: '度假海风与都市惬意感，干净利落的硬阴影与渐变晚霞。',
        prompt: '1980s Japanese City Pop aesthetic illustration by Hiroshi Nagai and Eizin Suzuki, a coastal street with a vintage yellow tram, palm trees, glowing sunset ocean horizon, pastel gradient sky, clean flat shadows, retro 80s album cover art --ar 16:9',
        keyModifiers: ['1980s Japanese City Pop aesthetic', 'Hiroshi Nagai style', 'pastel gradient sky', 'clean flat shadows', 'retro 80s album cover art']
      },
      {
        id: 'scene_b_08_artnouveau',
        number: '08',
        nameCn: '新艺术运动',
        nameEn: 'Art Nouveau Architecture',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_b_08_artnouveau.jpg',
        hasImage: true,
        tags: ['铁艺路灯曲线', '花卉装饰边框', '石版画典雅'],
        master: 'Alphonse Mucha',
        colorTone: '古铜金、橄榄绿与夕阳暖橙',
        technique: '铁艺路灯、轨道与植物花藤的有机曲线互相交织。',
        prompt: 'Art Nouveau illustration of a coastal tram street at twilight, Alphonse Mucha style, elegant sinuous flowing lines on iron lamp posts and rails, decorative botanical frame, golden sunset accents, vintage lithograph art --ar 16:9',
        keyModifiers: ['Art Nouveau illustration', 'Alphonse Mucha style', 'sinuous flowing lines', 'decorative botanical frame', 'golden sunset accents']
      },
      {
        id: 'scene_b_09_artdeco',
        number: '09',
        nameCn: '装饰风艺术',
        nameEn: 'Art Deco Urban',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_b_09_artdeco.jpg',
        hasImage: true,
        tags: ['流线型电车', '几何透视', '黑金奢华'],
        master: 'Tamara de Lempicka',
        colorTone: '曜石黑、香槟金与金属银灰',
        technique: '流线型车体与建筑强透视，展现20年代工业奢华。',
        prompt: 'Art Deco illustration of a coastal city street with a streamlined vintage yellow tram at twilight, sleek geometric architectural lines, radiant gold and navy blue palette, dramatic 1920s symmetrical perspective, Gatsby luxury --ar 16:9',
        keyModifiers: ['Art Deco illustration', 'sleek geometric architectural lines', 'radiant gold and navy blue palette', 'Gatsby luxury']
      },
      {
        id: 'scene_b_10_cyberpunk',
        number: '10',
        nameCn: '赛博朋克霓虹',
        nameEn: 'Cyberpunk Tram City',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_b_10_cyberpunk.jpg',
        hasImage: true,
        tags: ['磁悬浮列车', '霓虹招牌倒影', '雨雾光束'],
        master: 'Syd Mead / Blade Runner',
        colorTone: '青蓝 (Cyan) 与荧光洋红 (Magenta)',
        technique: '发光悬浮列车穿梭在雨雾霓虹大厦之间，水洼倒影璀璨。',
        prompt: 'Cyberpunk neon illustration of a futuristic tram crossing a rain-drenched coastal city intersection at night, vibrant glowing cyan and magenta holographic signs, steam rising, glossy wet asphalt reflections, Blade Runner aesthetic --ar 16:9',
        keyModifiers: ['Cyberpunk neon illustration', 'glowing cyan and magenta holographic signs', 'glossy wet asphalt reflections', 'Blade Runner aesthetic']
      },
      {
        id: 'scene_b_11_ghibli',
        number: '11',
        nameCn: '吉卜力 / 赛璐珞平涂',
        nameEn: 'Studio Ghibli Seaside',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_b_11_ghibli.jpg',
        hasImage: true,
        tags: ['海边小镇', '江之电感', '蓬松积雨云'],
        master: '男鹿和雄 / 宫崎骏',
        colorTone: '青绿海岛、黄色江之电与纯白积雨云',
        technique: '经典江之岛海滨手绘风光，云朵层次丰富，治愈感十足。',
        prompt: 'Anime cel-shaded landscape in the style of Studio Ghibli and Makoto Shinkai, a seaside town street with a vintage yellow tram after summer rain, fluffy sunset clouds, sparkling lens flares, Kazuo Oga painted scenery, heartwarming nostalgia --ar 16:9',
        keyModifiers: ['Anime cel-shaded landscape', 'Studio Ghibli style', 'Kazuo Oga painted scenery', 'sparkling lens flares', 'heartwarming nostalgia']
      },
      {
        id: 'scene_b_12_flatvector',
        number: '12',
        nameCn: '极简扁平矢量',
        nameEn: 'Minimalist Flat Vector',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_b_12_flatvector.jpg',
        hasImage: true,
        tags: ['纯色剪影', '极简海平线', '几何色块'],
        master: 'Malika Favre',
        colorTone: '深邃群青、亮黄与珊瑚橙',
        technique: '剔除复杂细节，用利落几何形状勾勒电车与海平线。',
        prompt: 'Minimalist flat vector graphic illustration by Malika Favre of a coastal tram intersection at sunset, bold geometric shapes, high contrast negative space, razor-sharp clean edges, chic modern travel poster --ar 16:9',
        keyModifiers: ['Minimalist flat vector graphic illustration', 'Malika Favre style', 'bold geometric shapes', 'high contrast negative space', 'razor-sharp clean edges']
      },
      {
        id: 'scene_b_13_pixelart',
        number: '13',
        nameCn: '16-bit 像素风',
        nameEn: '16-bit Pixel Seaside',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_b_13_pixelart.jpg',
        hasImage: true,
        tags: ['点阵水洼', '街机横版', '像素落日'],
        master: 'SNES 街机大作',
        colorTone: '16色经典街机调色板',
        technique: '横版卷轴游戏视角，点阵水洼倒影与晚霞渐变网点。',
        prompt: '16-bit pixel art of a coastal city street intersection at twilight after rain, a vintage yellow tram passing, glowing streetlights reflected in puddles, meticulous pixel dithering, nostalgic retro 90s arcade aesthetic --ar 16:9',
        keyModifiers: ['16-bit pixel art', 'meticulous pixel dithering', 'glowing streetlights reflected in puddles', 'retro 90s arcade aesthetic']
      },
      {
        id: 'scene_b_14_crayon',
        number: '14',
        nameCn: '绘本蜡笔与拼贴',
        nameEn: 'Picture Book Story',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_b_14_crayon.jpg',
        hasImage: true,
        tags: ['童趣小镇', '蜡笔手感', '剪纸层次'],
        master: 'Eric Carle',
        colorTone: '暖黄、草绿与质朴赭石',
        technique: '撕纸贴画与粗颗粒油画棒涂抹，营造童话绘本故事感。',
        prompt: 'Whimsical children\'s picture book illustration of a cute yellow tram driving through a rainy coastal town at dusk, visible waxy crayon textures, soft oil pastels, torn paper collage elements, warm cozy storybook art --ar 16:9',
        keyModifiers: ['children\'s picture book illustration', 'visible waxy crayon textures', 'soft oil pastels', 'torn paper collage elements']
      }
    ]
  },
  {
    id: 'scene_c',
    title: 'III · 悬崖古树与镜湖',
    subtitle: '自然风光 · 远近层次与写意笔触',
    badge: '16:9 全景比例',
    description: '悬崖边缘盛开的孤树，俯瞰宁静镜面湖泊，远方雪山与晚霞落日。用于测试自然笔触、色彩渐变、水体质感、空气透视与写意度。',
    coreSubject: 'A solitary ancient blossoming cherry tree standing on a rocky cliff overlooking a serene alpine lake at sunset, distant snowy mountain peaks, dramatic clouds',
    aspectRatio: '16:9',
    styles: [
      {
        id: 'scene_c_01_impasto',
        number: '01',
        nameCn: '厚涂油画',
        nameEn: 'Impasto Oil Painting',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_c_01_impasto.jpg',
        hasImage: true,
        tags: ['粗粝岩石', '雕塑般花瓣', '暮光浓厚'],
        master: 'Craig Mullins / 梵高',
        colorTone: '暖金、赭石与普鲁士蓝山体',
        technique: '粗粝厚重的刮刀堆叠岩石与繁密花簇。',
        prompt: 'Impasto oil painting of a solitary blossoming cherry tree on a rocky cliff overlooking a serene alpine lake at sunset, distant snowy peaks, thick sculptural palette knife strokes, heavy oil paint texture, dramatic rich golden-hour lighting --ar 16:9',
        keyModifiers: ['Impasto oil painting', 'thick sculptural palette knife strokes', 'heavy oil paint texture', 'golden-hour lighting']
      },
      {
        id: 'scene_c_02_watercolor',
        number: '02',
        nameCn: '通透水彩',
        nameEn: 'Luminous Watercolor',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_c_02_watercolor.jpg',
        hasImage: true,
        tags: ['湖光山色', '空灵浸染', '留白诗意'],
        master: '吴冠中 / 现代水彩',
        colorTone: '淡粉樱花、水绿湖泊与冷灰远山',
        technique: '大面积湿画法晕染湖面与远方雪山，花瓣点缀其上。',
        prompt: 'Luminous watercolor landscape of an ancient blossoming tree on a cliff overlooking a calm alpine lake at sunset, distant mountains, translucent wet-on-wet bleeding washes, soft gradient skies, visible cold-press paper grain, delicate ink accents --ar 16:9',
        keyModifiers: ['Luminous watercolor landscape', 'translucent wet-on-wet bleeding washes', 'soft gradient skies', 'visible cold-press paper grain']
      },
      {
        id: 'scene_c_03_impressionism',
        number: '03',
        nameCn: '印象派与点彩',
        nameEn: 'Impressionist Landscape',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_c_03_impressionism.jpg',
        hasImage: true,
        tags: ['波光粼粼', '莫奈粉紫', '空气颤动'],
        master: 'Claude Monet',
        colorTone: '粉紫晚霞、金橙倒影与群青水面',
        technique: '点状纯色笔触捕捉水面落日反光与空气颤动感。',
        prompt: 'Impressionist oil painting of a blossoming tree on a cliff overlooking a serene lake at sunset, loose dappled brushstrokes, Claude Monet style, vibrant flickering color spots, shimmering water surface, atmospheric light vibration --ar 16:9',
        keyModifiers: ['Impressionist oil painting', 'loose dappled brushstrokes', 'Claude Monet style', 'vibrant flickering color spots', 'shimmering water surface']
      },
      {
        id: 'scene_c_04_silkscreen',
        number: '04',
        nameCn: '丝网版画 / 波普',
        nameEn: 'Silkscreen Landscape',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_c_04_silkscreen.jpg',
        hasImage: true,
        tags: ['明丽色块', '自然版画', '套印美学'],
        master: 'Andy Warhol',
        colorTone: '荧光粉樱花、明黄天空与翠绿山体',
        technique: '波普艺术色彩分离与丝网多色套印。',
        prompt: 'Silkscreen screenprint artwork of a blossoming tree on a cliff overlooking a lake and distant mountains, bold flat color blocks, slight misregistration print offset, high contrast pop art style, Andy Warhol nature poster --ar 16:9',
        keyModifiers: ['Silkscreen screenprint artwork', 'bold flat color blocks', 'slight misregistration print offset', 'Andy Warhol nature poster']
      },
      {
        id: 'scene_c_05_ukiyoe',
        number: '05',
        nameCn: '浮世绘木刻版画',
        nameEn: 'Ukiyo-e Mount Fuji',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_c_05_ukiyoe.jpg',
        hasImage: true,
        tags: ['北斋樱花', '水墨山形', '和纸拓印'],
        master: '葛饰北斋《富岳三十六景》',
        colorTone: '富士山白雪、深黛青山脚与樱粉',
        technique: '经典的富士山远眺构图，前景樱花墨线勾勒，和纸肌理。',
        prompt: 'Authentic Japanese Ukiyo-e woodblock print of an ancient sakura tree on a cliff overlooking Mount Fuji and a calm lake at sunset, crisp black sumi-e outlines, flat mineral pigment washes, washi paper texture, Hokusai style --ar 16:9',
        keyModifiers: ['Japanese Ukiyo-e woodblock print', 'Hokusai style', 'crisp black sumi-e outlines', 'flat mineral pigment washes', 'washi paper texture']
      },
      {
        id: 'scene_c_06_vintage_comic',
        number: '06',
        nameCn: '美漫复古网点',
        nameEn: 'Vintage Comic Nature',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_c_06_vintage_comic.jpg',
        hasImage: true,
        tags: ['硬朗黑线', '网点晚霞', '复古科幻感'],
        master: 'Roy Lichtenstein',
        colorTone: '粗黑线条与四色网点渐变',
        technique: '美漫分镜构图，网点表现山体与湖水渐变。',
        prompt: 'Vintage 1960s comic book illustration of a blossoming tree on a cliff overlooking a mountain lake at sunset, Roy Lichtenstein style, prominent Ben-Day halftone dots, bold black ink contour lines, aged pulp paper texture --ar 16:9',
        keyModifiers: ['Vintage 1960s comic book illustration', 'Roy Lichtenstein style', 'prominent Ben-Day halftone dots', 'bold black ink contour lines']
      },
      {
        id: 'scene_c_07_citypop',
        number: '07',
        nameCn: 'City Pop 昭和复古',
        nameEn: 'City Pop Resort Nature',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_c_07_citypop.jpg',
        hasImage: true,
        tags: ['清透蓝粉', '度假湖泊', '永井博纯净'],
        master: 'Hiroshi Nagai',
        colorTone: '纯净天蓝、粉紫晚霞与明亮反光',
        technique: '永井博经典的度假风构图，宁静纯粹的色块搭配。',
        prompt: '1980s Japanese City Pop aesthetic illustration by Hiroshi Nagai, an ancient blooming tree on a cliff overlooking a crystal clear lake at sunset, distant purple mountains, pastel sky gradients, clean flat shadows, retro 80s resort vibe --ar 16:9',
        keyModifiers: ['1980s Japanese City Pop aesthetic', 'Hiroshi Nagai style', 'pastel sky gradients', 'clean flat shadows', 'retro 80s resort vibe']
      },
      {
        id: 'scene_c_08_artnouveau',
        number: '08',
        nameCn: '新艺术运动',
        nameEn: 'Art Nouveau Botanical',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_c_08_artnouveau.jpg',
        hasImage: true,
        tags: ['蜿蜒枝丫', '植物对称框', '金箔点缀'],
        master: 'Alphonse Mucha',
        colorTone: '香槟金、孔雀绿与古典象牙白',
        technique: '树枝自然延伸成优雅的装饰曲线，外围环绕金箔边框。',
        prompt: 'Art Nouveau landscape illustration of an ancient blossoming tree on a cliff over a lake at dusk, Alphonse Mucha style, sinuous organic floral branches, intricate decorative circular botanical frame, golden leaf accents, elegant lithograph --ar 16:9',
        keyModifiers: ['Art Nouveau landscape illustration', 'Alphonse Mucha style', 'sinuous organic floral branches', 'decorative circular botanical frame', 'golden leaf accents']
      },
      {
        id: 'scene_c_09_artdeco',
        number: '09',
        nameCn: '装饰风艺术',
        nameEn: 'Art Deco Grandeur',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_c_09_artdeco.jpg',
        hasImage: true,
        tags: ['几何太阳芒', '对称山体', '金绿奢华'],
        master: 'Tamara de Lempicka',
        colorTone: '曜石黑、翠绿与放射金芒',
        technique: '放射状对称的几何落日光芒与棱角分明的山峦。',
        prompt: 'Art Deco illustration of an ancient tree on a cliff overlooking a mountain lake at sunset, sleek geometric stylized branches, radiating gold and teal sunbeams, glamorous symmetrical 1920s Gatsby aesthetic --ar 16:9',
        keyModifiers: ['Art Deco illustration', 'sleek geometric stylized branches', 'radiating gold and teal sunbeams', 'Gatsby aesthetic']
      },
      {
        id: 'scene_c_10_cyberpunk',
        number: '10',
        nameCn: '赛博朋克全息',
        nameEn: 'Cyberpunk Holographic',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_c_10_cyberpunk.jpg',
        hasImage: true,
        tags: ['全息发光樱花', '远景赛博巨构', '电光湖面倒影'],
        master: 'Blade Runner / 未来概念设计',
        colorTone: '荧光青、品红激光与深黑夜幕',
        technique: '悬崖上的全息数码樱花树在暗夜中发光，湖面反射激光网格。',
        prompt: 'Cyberpunk sci-fi landscape of a glowing holographic sakura tree on a cliff overlooking a dark reflective lake, distant neon megacity spires under night sky, vivid cyan and magenta laser light, volumetric mist, Blade Runner vibe --ar 16:9',
        keyModifiers: ['Cyberpunk sci-fi landscape', 'glowing holographic sakura tree', 'neon megacity spires', 'vivid cyan and magenta laser light', 'Blade Runner vibe']
      },
      {
        id: 'scene_c_11_ghibli',
        number: '11',
        nameCn: '吉卜力 / 赛璐珞平涂',
        nameEn: 'Studio Ghibli Epic Vista',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_c_11_ghibli.jpg',
        hasImage: true,
        tags: ['男鹿和雄画风', '宏大云海', '治愈风光'],
        master: '男鹿和雄 / 宫崎骏',
        colorTone: '青翠草甸、澄澈湖蓝与壮丽晚霞',
        technique: '男鹿和雄式细腻水粉手绘大自然，壮阔而治愈。',
        prompt: 'Anime cel-shaded landscape in the style of Studio Ghibli, a giant blossoming cherry tree on a cliff overlooking a calm blue lake, distant snow mountains, massive fluffy sunset clouds, hand-painted Kazuo Oga background, heartwarming and breathtaking --ar 16:9',
        keyModifiers: ['Anime cel-shaded landscape', 'Studio Ghibli style', 'Kazuo Oga background', 'massive fluffy sunset clouds', 'heartwarming and breathtaking']
      },
      {
        id: 'scene_c_12_flatvector',
        number: '12',
        nameCn: '极简扁平矢量',
        nameEn: 'Minimalist Vector Mountain',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_c_12_flatvector.jpg',
        hasImage: true,
        tags: ['孤树剪影', '高反差负空间', '现代旅行海报'],
        master: 'Malika Favre',
        colorTone: '纯黑剪影、明橙落日与深蓝湖泊',
        technique: '极简矢量剪影构图，强烈的负空间现代艺术感。',
        prompt: 'Minimalist flat vector graphic illustration by Malika Favre, a silhouette of a solitary tree on a cliff over a calm lake at sunset, bold geometric color blocking, high contrast negative space, clean razor-sharp vector lines --ar 16:9',
        keyModifiers: ['Minimalist flat vector graphic illustration', 'Malika Favre style', 'bold geometric color blocking', 'high contrast negative space', 'razor-sharp vector lines']
      },
      {
        id: 'scene_c_13_pixelart',
        number: '13',
        nameCn: '16-bit 像素风',
        nameEn: '16-bit Pixel Landscape',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_c_13_pixelart.jpg',
        hasImage: true,
        tags: ['RPG大地图', '点阵雪山', '像素晚霞渐变'],
        master: 'SFC / 八方旅人风格',
        colorTone: '经典 16-bit 怀旧色盘',
        technique: '复古日系 RPG 史诗大地图风光，精细的像素抖动过渡。',
        prompt: '16-bit pixel art of an ancient blossoming tree on a cliff overlooking a calm alpine lake at sunset, distant snowy mountain peaks, glowing sky gradients, meticulous pixel dithering, nostalgic retro 90s RPG game vista --ar 16:9',
        keyModifiers: ['16-bit pixel art', 'meticulous pixel dithering', 'retro 90s RPG game vista', 'glowing sky gradients']
      },
      {
        id: 'scene_c_14_crayon',
        number: '14',
        nameCn: '绘本蜡笔与拼贴',
        nameEn: 'Picture Book Nature',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_c_14_crayon.jpg',
        hasImage: true,
        tags: ['童趣大树', '蜡笔波光', '剪贴自然'],
        master: 'Eric Carle',
        colorTone: '温暖草木绿、金黄与天真粉红',
        technique: '手工水彩刮色纸剪贴与蜡笔线条，充满生机与童真。',
        prompt: 'Whimsical children\'s picture book illustration of a giant blossoming tree on a cliff overlooking a quiet lake and mountains, visible waxy crayon strokes, soft oil pastel texture, layered collage paper cutouts, Eric Carle style --ar 16:9',
        keyModifiers: ['children\'s picture book illustration', 'visible waxy crayon strokes', 'soft oil pastel texture', 'layered collage paper cutouts', 'Eric Carle style']
      }
    ]
  },
  {
    id: 'scene_d',
    title: 'IV · 午夜古书店与老学者',
    subtitle: '室内群组 · 密集道具结构与昏暖光晕',
    badge: '16:9 全景比例',
    description: '高耸入顶的古旧胡桃木书架之间，满头银发的老学者戴着单片眼镜在黄铜台灯下研读泛黄古籍，微尘在暖光中飘散。用于测试复杂密集物体、纸本皮具材质、局部聚光与深邃空间氛围。',
    coreSubject: 'An elderly silver-haired scholar wearing wire-rimmed spectacles reading an ancient leatherbound tome under a warm brass lamp, surrounded by towering walnut bookshelves crammed with antique books in a cozy midnight library',
    aspectRatio: '16:9',
    styles: [
      {
        id: 'scene_d_01_impasto',
        number: '01',
        nameCn: '厚涂油画',
        nameEn: 'Impasto Oil Painting',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_d_01_impasto.jpg',
        hasImage: true,
        tags: ['油画刀堆叠', '古籍肌理', '明暗对照法', '厚重笔触'],
        master: 'Craig Mullins / 伦勃朗',
        colorTone: '浓郁熟褐、羊皮纸焦黄与烛台金光',
        technique: '运用油画刀在古旧书本与老学者面部堆叠厚实色层，强烈明暗对比塑造沉浸感。',
        prompt: 'Impasto oil painting of an elderly silver-haired scholar wearing wire-rimmed spectacles reading an ancient leatherbound book under a warm brass lamp, surrounded by towering walnut bookshelves crammed with antique books in a cozy midnight library, thick visible palette knife strokes, heavy textured oil paint, rich chiaroscuro lighting, Craig Mullins style, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['impasto oil painting', 'thick visible palette knife strokes', 'heavy textured oil paint', 'rich chiaroscuro lighting', 'Craig Mullins style']
      },
      {
        id: 'scene_d_02_watercolor',
        number: '02',
        nameCn: '通透水彩',
        nameEn: 'Luminous Watercolor',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_d_02_watercolor.jpg',
        hasImage: true,
        tags: ['湿画晕染', '烛光透光', '冷压纸纹', '墨线淡彩'],
        master: 'Sargent / 现代水彩插画',
        colorTone: '琥珀暖黄、冷杉绿与灰紫阴影',
        technique: '利用水分在冷压水彩纸上的自然扩散表现灯光在书架缝隙间的穿透与漫射。',
        prompt: 'Luminous watercolor painting of an elderly silver-haired scholar wearing wire-rimmed spectacles reading a vintage leatherbound book under a warm brass lamp, towering antique bookshelves in a cozy midnight library, wet-on-wet bleeding washes, translucent watercolor pigments, visible cold-press paper grain, delicate soft ink lines, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['luminous watercolor painting', 'wet-on-wet bleeding washes', 'translucent watercolor pigments', 'visible cold-press paper grain', 'delicate soft ink lines']
      },
      {
        id: 'scene_d_03_impressionism',
        number: '03',
        nameCn: '印象派与点彩',
        nameEn: 'Impressionist Oil',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_d_03_impressionism.jpg',
        hasImage: true,
        tags: ['光斑颤动', '室内暖光', '并置碎笔', '莫奈光影'],
        master: '莫奈 (Monet) / 德加 (Degas)',
        colorTone: '金色灯火、蓝灰书影与暖橙光晕',
        technique: '以跳跃的纯色碎笔捕捉灯火在老学者白发与镜片上的瞬间反光。',
        prompt: 'Impressionist oil painting of an elderly scholar reading an old book under a warm brass lamp in a midnight library filled with bookshelves, Claude Monet style, loose flickering brushstrokes, vibrant unmixed color vibration, warm ambient candlelight and lamplight, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['impressionist oil painting', 'Claude Monet style', 'loose flickering brushstrokes', 'vibrant unmixed color vibration', 'warm ambient candlelight']
      },
      {
        id: 'scene_d_04_silkscreen',
        number: '04',
        nameCn: '丝网版画 / 波普艺术',
        nameEn: 'Silkscreen / Pop Art',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_d_04_silkscreen.jpg',
        hasImage: true,
        tags: ['高饱和色块', '印刷错版', '波普海报', '硬边对位'],
        master: '安迪·沃霍尔 (Andy Warhol)',
        colorTone: '荧光柠檬黄、群青与品红对撞',
        technique: '多层丝网套印将古典书房转化为现代波普视觉符号，带印刷微错位质感。',
        prompt: 'Silkscreen screenprint pop art of an elderly scholar reading an antique book under a lamp in a library with towering bookshelves, Andy Warhol graphic poster aesthetic, bold flat color blocks, slight misregistration print offset, high contrast, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['silkscreen screenprint pop art', 'Andy Warhol graphic poster aesthetic', 'bold flat color blocks', 'slight misregistration print offset']
      },
      {
        id: 'scene_d_05_ukiyoe',
        number: '05',
        nameCn: '浮世绘木刻版画',
        nameEn: 'Japanese Ukiyo-e',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_d_05_ukiyoe.jpg',
        hasImage: true,
        tags: ['墨线勾勒', '矿物颜料', '和纸纤维', '和风灯笼'],
        master: '葛饰北斋 / 歌川广重',
        colorTone: '普鲁士蓝、浅米和纸色与朱砂红印',
        technique: '严谨工细的雕版墨线，古朴矿物色平涂与纸面微细木纹肌理。',
        prompt: 'Authentic Japanese Ukiyo-e woodblock print of an elderly scholar reading an ancient scroll under a paper lantern surrounded by tall wooden bookshelves in a midnight library, crisp black sumi-e outlines, flat mineral pigment washes, washi paper texture, Hokusai and Hiroshige style, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['Japanese Ukiyo-e woodblock print', 'crisp black sumi-e outlines', 'flat mineral pigment washes', 'washi paper texture', 'Hokusai style']
      },
      {
        id: 'scene_d_06_vintage_comic',
        number: '06',
        nameCn: '美漫复古网点',
        nameEn: 'Vintage Comic / Ben-Day Dots',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_d_06_vintage_comic.jpg',
        hasImage: true,
        tags: ['本戴网点', '叙事分镜', '粗黑墨线', '复古印刷'],
        master: '罗伊·利希滕斯坦 (Roy Lichtenstein)',
        colorTone: 'CMYK 原色体系、做旧新闻纸黄',
        technique: '60年代美漫印刷风格，密集彩色网点构建老学者与古籍的阴影层次。',
        prompt: 'Vintage 1960s comic book illustration of an elderly scholar reading a mysterious glowing ancient book in a midnight library, Roy Lichtenstein style, prominent Ben-Day halftone dots, bold black ink contour lines, dramatic comic narrative panel, aged pulp paper texture, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['vintage 1960s comic book illustration', 'Roy Lichtenstein style', 'prominent Ben-Day halftone dots', 'bold black ink contour lines', 'aged pulp paper texture']
      },
      {
        id: 'scene_d_07_citypop',
        number: '07',
        nameCn: 'City Pop 昭和复古',
        nameEn: '1980s City Pop Aesthetic',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_d_07_citypop.jpg',
        hasImage: true,
        tags: ['霓虹夜色', '干净几何阴影', '粉紫渐变', '昭和现代'],
        master: '永井博 (Hiroshi Nagai)',
        colorTone: '薄荷绿、粉紫夜幕、鹅黄灯火',
        technique: '大面积纯净色块过渡，窗外都市霓虹与室内温暖台灯的几何硬阴影。',
        prompt: '1980s Japanese City Pop aesthetic illustration by Hiroshi Nagai, an elderly scholar reading a book by a large glass window in a modern retro bookstore at night, warm interior glow against neon city lights outside, clean flat geometric shadows, vibrant pastel gradients, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['1980s Japanese City Pop aesthetic', 'Hiroshi Nagai style', 'clean flat geometric shadows', 'vibrant pastel gradients']
      },
      {
        id: 'scene_d_08_artnouveau',
        number: '08',
        nameCn: '新艺术运动',
        nameEn: 'Art Nouveau Masterpiece',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_d_08_artnouveau.jpg',
        hasImage: true,
        tags: ['植物藤蔓', '对称花饰框', '烫金点缀', '典雅石版画'],
        master: '阿尔丰斯·慕夏 (Alphonse Mucha)',
        colorTone: '复古金、象牙白、鼠尾草绿与丁香紫',
        technique: '书架与书卷自然融入流动藤蔓曲线，外围雕琢华丽对称植物装饰边框。',
        prompt: 'Art Nouveau masterpiece illustration of an elderly scholar reading an ornate antique grimoire in a library with carved floral walnut bookshelves, Alphonse Mucha style, flowing sinuous organic vines, intricate decorative border, golden foil accents, elegant lithograph, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['Art Nouveau masterpiece illustration', 'Alphonse Mucha style', 'flowing sinuous organic vines', 'intricate decorative border', 'golden foil accents']
      },
      {
        id: 'scene_d_09_artdeco',
        number: '09',
        nameCn: '装饰风艺术',
        nameEn: 'Art Deco Luxury',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_d_09_artdeco.jpg',
        hasImage: true,
        tags: ['几何阶梯拱门', '黑金奢华', '流线型线条', '盖茨比美学'],
        master: '塔玛拉·德·蓝披卡 (Tamara de Lempicka)',
        colorTone: '曜石黑、香槟金与祖母绿',
        technique: '放射状对称的几何线条将宏伟图书馆转化为锋利、典雅的摩登装饰画。',
        prompt: '1920s Art Deco illustration of an elderly scholar reading a book in a majestic geometric library, luxurious gold and emerald green color palette, bold symmetrical stepped arches, sleek streamlined ornamentation, Great Gatsby aesthetic, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['1920s Art Deco illustration', 'luxurious gold and emerald green palette', 'bold symmetrical stepped arches', 'sleek streamlined ornamentation']
      },
      {
        id: 'scene_d_10_cyberpunk',
        number: '10',
        nameCn: '赛博朋克霓虹',
        nameEn: 'Cyberpunk Cyber-Archive',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_d_10_cyberpunk.jpg',
        hasImage: true,
        tags: ['全息光典', '赛博义体', '数字记忆水晶', '冷调雨夜'],
        master: '《银翼杀手》 / Syd Mead',
        colorTone: '霓虹青 (Cyan)、琥珀金与深黑服务器群',
        technique: '老学者化身义体档案官，在巨型数据阵列中翻阅悬浮发光的全息古籍。',
        prompt: 'Cyberpunk sci-fi illustration of an elderly cyborg scholar reading a glowing holographic codex in a dark high-tech archive tower, towering servers and digital memory crystals, neon cyan and amber circuit lights, Blade Runner atmosphere, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['Cyberpunk sci-fi illustration', 'glowing holographic codex', 'towering servers and digital memory crystals', 'neon cyan and amber circuit lights', 'Blade Runner atmosphere']
      },
      {
        id: 'scene_d_11_ghibli',
        number: '11',
        nameCn: '吉卜力 / 赛璐珞平涂',
        nameEn: 'Studio Ghibli Nostalgia',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_d_11_ghibli.jpg',
        hasImage: true,
        tags: ['水粉手绘背景', '温馨浮尘', '治愈老书房', '赛璐珞光影'],
        master: '男鹿和雄 / 宫崎骏',
        colorTone: '温暖原木褐、泛黄纸页色与柔光金黄',
        technique: '细腻手绘木质质感与漂浮微尘，充满宫崎骏电影般触手可及的温暖生活气息。',
        prompt: 'Studio Ghibli style cel-shaded anime background of an elderly silver-haired scholar reading a magical antique book in a warm cluttered wooden bookstore at midnight, cozy floating dust motes, gentle whimsical lighting, Hayao Miyazaki aesthetic, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['Studio Ghibli style', 'Hayao Miyazaki aesthetic', 'warm cluttered wooden bookstore', 'cozy floating dust motes', 'gentle whimsical lighting']
      },
      {
        id: 'scene_d_12_flatvector',
        number: '12',
        nameCn: '极简扁平矢量',
        nameEn: 'Minimalist Flat Vector',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_d_12_flatvector.jpg',
        hasImage: true,
        tags: ['负空间剪影', '极简书架', '锋利边缘', '现代插画海报'],
        master: 'Malika Favre',
        colorTone: '深夜蓝、暖焦糖色与纯白高光',
        technique: '摒弃所有繁杂细节，仅用几个精准纯粹的几何色块勾勒出老学者与书海。',
        prompt: 'Minimalist flat vector illustration of an elderly scholar reading a book under a warm lamp in a minimalist bookstore, Malika Favre style, bold negative space, high contrast silhouette, clean geometric vector shapes, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['Minimalist flat vector illustration', 'Malika Favre style', 'bold negative space', 'high contrast silhouette', 'clean geometric vector shapes']
      },
      {
        id: 'scene_d_13_pixelart',
        number: '13',
        nameCn: '16-bit 像素风',
        nameEn: '16-bit Pixel Library',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_d_13_pixelart.jpg',
        hasImage: true,
        tags: ['经典RPG场景', '点阵书架', '抖动暖光', '怀旧像素'],
        master: 'SNES 黄金时代像素大师',
        colorTone: '16-bit 暖褐、铜黄与墨绿色盘',
        technique: '纯手工像素点阵铺设，密布书架与老学者的每一个像素均有精巧的明暗过渡。',
        prompt: '16-bit pixel art of an elderly scholar reading a book in a cozy midnight library under a warm desk lamp, nostalgic retro RPG aesthetic, detailed pixel texture, warm dithering shadows, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['16-bit pixel art', 'nostalgic retro RPG aesthetic', 'detailed pixel texture', 'warm dithering shadows']
      },
      {
        id: 'scene_d_14_crayon',
        number: '14',
        nameCn: '绘本蜡笔与拼贴',
        nameEn: 'Picture Book / Crayon Collage',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_d_14_crayon.jpg',
        hasImage: true,
        tags: ['童趣老爷爷', '蜡笔手绘', '撕纸质感', '温暖绘本'],
        master: 'Eric Carle / Oliver Jeffers',
        colorTone: '温暖土黄、彩虹书脊与质朴纯白',
        technique: '用粗粝油画棒和带撕边纹理的彩色手工纸拼贴，带来纯真温暖的绘本故事感。',
        prompt: 'Children\'s picture book illustration in Eric Carle style, an elderly friendly scholar reading a large storybook in a whimsical library, rich waxy crayon textures, hand-painted textured paper collage, warm charming naive art, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['Children\'s picture book illustration', 'Eric Carle style', 'rich waxy crayon textures', 'hand-painted textured paper collage', 'warm charming naive art']
      }
    ]
  },
  {
    id: 'scene_e',
    title: 'V · 云海机械飞艇与悬空港',
    subtitle: '奇幻工业 · 复杂机械结构与金色云海光效',
    badge: '16:9 全景比例',
    description: '巨大而精密的黄铜机械飞艇停泊在悬空的复古铸铁塔楼港口，齿轮转动与排气管道蒸腾出白色烟雾，金色日出曙光穿透翻滚云海。用于测试宏大机械透视、金属光泽质感、多层体积云与强逆光表现。',
    coreSubject: 'A massive ornate brass steampunk airship docked at a floating gothic iron tower platform high above a sea of clouds at golden sunrise, spinning bronze gears and billowing white steam vents, glowing horizon light',
    aspectRatio: '16:9',
    styles: [
      {
        id: 'scene_e_01_impasto',
        number: '01',
        nameCn: '厚涂油画',
        nameEn: 'Impasto Oil Painting',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_e_01_impasto.jpg',
        hasImage: true,
        tags: ['厚重黄铜肌理', '刮刀云层', '朝阳金光', '史诗体积感'],
        master: 'Craig Mullins / 透纳 (J.M.W. Turner)',
        colorTone: '金红曙光、黄铜暗金与铸铁深青',
        technique: '厚堆颜料塑造翻滚的金色朝霞云海，油画刀凌厉刮出飞艇龙骨与铸铁港口。',
        prompt: 'Impasto oil painting of a massive ornate brass steampunk airship docked at a floating iron tower harbor above a vast sea of clouds at golden sunrise, thick visible palette knife strokes, heavy textured oil paint, rich chiaroscuro lighting, Craig Mullins style, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['impasto oil painting', 'thick visible palette knife strokes', 'heavy textured oil paint', 'Craig Mullins style', 'rich chiaroscuro lighting']
      },
      {
        id: 'scene_e_02_watercolor',
        number: '02',
        nameCn: '通透水彩',
        nameEn: 'Luminous Watercolor',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_e_02_watercolor.jpg',
        hasImage: true,
        tags: ['透光云海', '金属渗色', '水彩蒸汽', '空气远近感'],
        master: '透纳 / 现代概念水彩',
        colorTone: '透光暖金、天青色与铜绿',
        technique: '湿画晕染将庞大云海与蒸汽表现得轻盈通透，细腻墨线勾勒出精密机械齿轮。',
        prompt: 'Luminous watercolor painting of a steampunk brass airship docked at a sky platform amidst towering golden sunrise clouds, wet-on-wet bleeding washes, translucent watercolor pigments, visible cold-press paper grain, delicate mechanical line work, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['luminous watercolor painting', 'wet-on-wet bleeding washes', 'translucent watercolor pigments', 'visible cold-press paper grain', 'delicate mechanical line work']
      },
      {
        id: 'scene_e_03_impressionism',
        number: '03',
        nameCn: '印象派与点彩',
        nameEn: 'Impressionist Oil',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_e_03_impressionism.jpg',
        hasImage: true,
        tags: ['晨曦光斑', '工业蒸汽', '碎笔色彩并置', '莫奈日出印象'],
        master: '莫奈 (Monet) / 透纳',
        colorTone: '粉紫与橙黄交织的晨光、群青暗部',
        technique: '以《日出·印象》般的碎小光斑捕捉阳光照射在飞艇反光外壳与烟雾上的瞬时光影。',
        prompt: 'Impressionist oil painting of a majestic steampunk airship floating over golden clouds at sunrise, Claude Monet style, loose flickering brushstrokes, vibrant unmixed color vibration, shimmering atmospheric dawn light, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['impressionist oil painting', 'Claude Monet style', 'loose flickering brushstrokes', 'vibrant unmixed color vibration', 'shimmering atmospheric dawn light']
      },
      {
        id: 'scene_e_04_silkscreen',
        number: '04',
        nameCn: '丝网版画 / 波普艺术',
        nameEn: 'Silkscreen / Pop Art',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_e_04_silkscreen.jpg',
        hasImage: true,
        tags: ['机械波普', '撞色平涂', '版画粗糙质感', '复古工业海报'],
        master: '安迪·沃霍尔 (Andy Warhol)',
        colorTone: '铬黄、钴蓝、洋红与粗黑印线',
        technique: '高对比度色块平涂与错位丝网套印，赋予蒸汽朋克机械现代工业波普张力。',
        prompt: 'Silkscreen screenprint pop art of a steampunk mechanical airship docked at a sky harbor over clouds, Andy Warhol graphic poster aesthetic, bold flat color blocks, slight misregistration print offset, high contrast, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['silkscreen screenprint pop art', 'Andy Warhol graphic poster aesthetic', 'bold flat color blocks', 'slight misregistration print offset']
      },
      {
        id: 'scene_e_05_ukiyoe',
        number: '05',
        nameCn: '浮世绘木刻版画',
        nameEn: 'Japanese Ukiyo-e',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_e_05_ukiyoe.jpg',
        hasImage: true,
        tags: ['和风龙形飞舟', '卷云纹理', '木版套色', '葛饰北斋构图'],
        master: '葛饰北斋 / 歌川国芳',
        colorTone: '本蓝、赭石、胡粉白与金黄',
        technique: '将传统浮世绘波涛卷云纹融入天空，巨大机械飞艇以木刻墨线与矿物色展现。',
        prompt: 'Authentic Japanese Ukiyo-e woodblock print of a fantastical dragon-shaped flying ship anchored at a mountain sky port above sea of clouds at dawn, crisp black sumi-e outlines, flat mineral pigment washes, washi paper texture, Hokusai style, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['Japanese Ukiyo-e woodblock print', 'crisp black sumi-e outlines', 'flat mineral pigment washes', 'washi paper texture', 'Hokusai style']
      },
      {
        id: 'scene_e_06_vintage_comic',
        number: '06',
        nameCn: '美漫复古网点',
        nameEn: 'Vintage Comic / Ben-Day Dots',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_e_06_vintage_comic.jpg',
        hasImage: true,
        tags: ['探险连环画', '网点爆炸光芒', '美漫黑白强线', '黄金时代'],
        master: '罗伊·利希滕斯坦 (Roy Lichtenstein)',
        colorTone: 'CMYK 高饱和红黄蓝、老纸做旧色',
        technique: '20世纪黄金时代科幻漫画封面风格，密集的 Ben-Day 网点表现天空云雾与金属反光。',
        prompt: 'Vintage 1960s comic book illustration of a giant steampunk flying battleship soaring into a sky harbor, Roy Lichtenstein style, prominent Ben-Day halftone dots, bold black ink contour lines, dynamic retro pulp adventure panel, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['vintage 1960s comic book illustration', 'Roy Lichtenstein style', 'prominent Ben-Day halftone dots', 'bold black ink contour lines']
      },
      {
        id: 'scene_e_07_citypop',
        number: '07',
        nameCn: 'City Pop 昭和复古',
        nameEn: '1980s City Pop Aesthetic',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_e_07_citypop.jpg',
        hasImage: true,
        tags: ['空中游艇', '粉紫云霞', '几何硬影', '复古未来度假'],
        master: '永井博 (Hiroshi Nagai)',
        colorTone: '海蓝、粉紫落日渐变、铬黄与乳白',
        technique: '复古未来主义空中巡洋舰，极其干净利落的几何硬阴影与梦幻粉紫日落云霞。',
        prompt: '1980s Japanese City Pop aesthetic illustration by Hiroshi Nagai, a sleek retro-futuristic sky cruiser docked at an art-deco skyport at sunset, pastel gradient dusk clouds, flat clean shadows, resort sky vacation mood, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['1980s Japanese City Pop aesthetic', 'Hiroshi Nagai style', 'pastel gradient dusk clouds', 'clean flat shadows', 'resort sky vacation mood']
      },
      {
        id: 'scene_e_08_artnouveau',
        number: '08',
        nameCn: '新艺术运动',
        nameEn: 'Art Nouveau Masterpiece',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_e_08_artnouveau.jpg',
        hasImage: true,
        tags: ['蜻蜓机械翼', '植物铁艺塔楼', '流动曲线', '慕夏华丽边框'],
        master: '阿尔丰斯·慕夏 (Alphonse Mucha)',
        colorTone: '香槟金、橄榄绿、孔雀蓝与复古铜',
        technique: '飞艇骨架化为优雅的昆虫有机翅膀，悬空港口融入慕夏标志性的华丽铸铁花蔓。',
        prompt: 'Art Nouveau masterpiece illustration of a gilded steampunk airship with dragonfly wings docking at an iron floral tower above clouds, Alphonse Mucha style, flowing sinuous organic lines, intricate decorative border, golden foil accents, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['Art Nouveau masterpiece illustration', 'Alphonse Mucha style', 'flowing sinuous organic lines', 'intricate decorative border', 'golden foil accents']
      },
      {
        id: 'scene_e_09_artdeco',
        number: '09',
        nameCn: '装饰风艺术',
        nameEn: 'Art Deco Sky Port',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_e_09_artdeco.jpg',
        hasImage: true,
        tags: ['流线型齐柏林', '摩天楼尖顶', '对称金芒', '大都会美学'],
        master: 'Tamara de Lempicka / 《大都会》',
        colorTone: '曜石黑、流金、铬银与海军蓝',
        technique: '流线型极简金属曲面与帝国大厦般尖锐挺拔的几何对称，尽显工业巅峰奢华。',
        prompt: '1920s Art Deco illustration of a monumental streamlined luxury zeppelin airship docking at a towering skyscraper spire above golden clouds, sleek geometric symmetries, rich gold and midnight blue palette, Great Gatsby aesthetic, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['1920s Art Deco illustration', 'sleek geometric symmetries', 'rich gold and midnight blue palette', 'Great Gatsby aesthetic']
      },
      {
        id: 'scene_e_10_cyberpunk',
        number: '10',
        nameCn: '赛博朋克霓虹',
        nameEn: 'Cyberpunk Sky Barge',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_e_10_cyberpunk.jpg',
        hasImage: true,
        tags: ['重工业空艇', '等离子推进器', '全息高塔', '工业雾霾'],
        master: '《银翼杀手》 / Syd Mead',
        colorTone: '推进器电光橙、全息青绿与深黑金属',
        technique: '粗粝庞大的重工业飞船在电光闪烁的赛博高塔间靠泊，浓厚烟雾反射高亮光芒。',
        prompt: 'Cyberpunk sci-fi illustration of a massive neon-lit heavy industrial sky cruiser docking at a smoggy megacity sky-dock station above clouds at night, glowing cyan and orange thrusters, Blade Runner atmosphere, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['Cyberpunk sci-fi illustration', 'massive neon-lit heavy industrial sky cruiser', 'glowing cyan and orange thrusters', 'Blade Runner atmosphere']
      },
      {
        id: 'scene_e_11_ghibli',
        number: '11',
        nameCn: '吉卜力 / 赛璐珞平涂',
        nameEn: 'Studio Ghibli Sky Castle',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_e_11_ghibli.jpg',
        hasImage: true,
        tags: ['天空之城画风', '蓬松积雨云', '手绘机械感', '清新治愈'],
        master: '男鹿和雄 / 宫崎骏 (Laputa)',
        colorTone: '蔚蓝天穹、棉花白云海与原木铜黄',
        technique: '致敬《天空之城》的手绘机械美学，蓬松有体量的积雨云与充满温度的机件细节。',
        prompt: 'Studio Ghibli style cel-shaded anime background of a whimsical wooden and brass airship docking at a floating sky castle among cumulus clouds at sunrise, Hayao Miyazaki Laputa aesthetic, lush painterly clouds, hand-drawn warmth, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['Studio Ghibli style', 'Hayao Miyazaki Laputa aesthetic', 'lush painterly clouds', 'hand-drawn warmth']
      },
      {
        id: 'scene_e_12_flatvector',
        number: '12',
        nameCn: '极简扁平矢量',
        nameEn: 'Minimalist Airship Vector',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_e_12_flatvector.jpg',
        hasImage: true,
        tags: ['几何飞艇剪影', '分层云海', '高反差负空间', '航空海报'],
        master: 'Malika Favre',
        colorTone: '深夜青、日落金、暖橙与纯白',
        technique: '运用极简几何弧线勾勒飞艇剪影，与层层推进的扁平云海构成视觉张力。',
        prompt: 'Minimalist flat vector illustration of a steampunk airship sailing above rolling clouds at sunrise, Malika Favre style, bold negative space, high contrast silhouette, clean geometric vector shapes, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['Minimalist flat vector illustration', 'Malika Favre style', 'bold negative space', 'high contrast silhouette', 'clean geometric vector shapes']
      },
      {
        id: 'scene_e_13_pixelart',
        number: '13',
        nameCn: '16-bit 像素风',
        nameEn: '16-bit Airship Odyssey',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_e_13_pixelart.jpg',
        hasImage: true,
        tags: ['经典RPG飞空艇', '多重滚屏云层', '点阵齿轮', '90年代街机'],
        master: '最终幻想 / 八方旅人风格',
        colorTone: 'SFC 黄金时代 16-bit 工业调色盘',
        technique: '细腻像素点阵呈现飞艇螺旋桨与云雾层次，宛如 90 年代经典 RPG 巅峰过场。',
        prompt: '16-bit pixel art of a steampunk airship docked at a sky platform above animated cloud layers at dawn, nostalgic retro 90s RPG airship aesthetic, crisp pixel details, warm dithering sky, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['16-bit pixel art', 'nostalgic retro 90s RPG airship aesthetic', 'crisp pixel details', 'warm dithering sky']
      },
      {
        id: 'scene_e_14_crayon',
        number: '14',
        nameCn: '绘本蜡笔与拼贴',
        nameEn: 'Picture Book / Crayon Collage',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_e_14_crayon.jpg',
        hasImage: true,
        tags: ['童梦飞船', '蜡笔云朵', '彩色手工纸', '纯真质朴'],
        master: 'Eric Carle',
        colorTone: '阳光暖黄、童趣天蓝与斑斓纸屑色',
        technique: '剪贴质感的棉花糖云朵与稚拙可爱的蜡笔线条飞艇，洋溢童年幻想。',
        prompt: 'Children\'s picture book illustration in Eric Carle style, a colorful whimsical flying ship floating over puffy clouds at sunrise, rich waxy crayon textures, hand-painted textured paper collage, playful naive art, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['Children\'s picture book illustration', 'Eric Carle style', 'rich waxy crayon textures', 'hand-painted textured paper collage', 'playful naive art']
      }
    ]
  },
  {
    id: 'scene_f',
    title: 'VI · 深海发光水母与探险潜水员',
    subtitle: '幽暗水下 · 生物自发光折射与高对比暗调',
    badge: '16:9 全景比例',
    description: '幽蓝神秘的深海断崖前，数只巨大的半透明发光水母散发着青蓝与粉紫的荧光脉动，身穿复古铜盔潜水服的探险者手持聚光探照灯在珊瑚礁旁探索。用于测试暗调高动态范围、透明自发光材质、水下折射光斑与深邃空间感。',
    coreSubject: 'A deep sea diver in a vintage bronze diving suit holding a glowing underwater torch, exploring near giant translucent bioluminescent jellyfish in deep oceanic abyss, floating particles and vibrant underwater luminescence',
    aspectRatio: '16:9',
    styles: [
      {
        id: 'scene_f_01_impasto',
        number: '01',
        nameCn: '厚涂油画',
        nameEn: 'Impasto Oil Painting',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_f_01_impasto.jpg',
        hasImage: true,
        tags: ['深海厚重肌理', '荧光刮刀厚堆', '强暗明暗对比', '深海氛围'],
        master: 'Craig Mullins / 伦勃朗',
        colorTone: '幽深海蓝、荧光青与铜盔暖黄',
        technique: '深厚油彩堆叠出深海幽邃感，发光水母以厚重纯色颜料直接刮涂，光感灼目。',
        prompt: 'Impasto oil painting of a deep sea diver in a vintage bronze helmet suit surrounded by giant glowing bioluminescent jellyfish in deep dark ocean, thick visible palette knife strokes, heavy textured oil paint, rich chiaroscuro glow, Craig Mullins style, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['impasto oil painting', 'thick visible palette knife strokes', 'heavy textured oil paint', 'Craig Mullins style', 'rich chiaroscuro glow']
      },
      {
        id: 'scene_f_02_watercolor',
        number: '02',
        nameCn: '通透水彩',
        nameEn: 'Luminous Watercolor',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_f_02_watercolor.jpg',
        hasImage: true,
        tags: ['透明水光晕染', '水下波光流动', '水母半透明感', '湿画沉淀'],
        master: '现代光影水彩',
        colorTone: '群青、孔雀绿、紫罗兰与夜光白',
        technique: '借由水彩水分的天然流动与颜料颗粒沉淀，将水母的胶质半透明与深海波光完美呈现。',
        prompt: 'Luminous watercolor painting of a deep sea diver swimming amongst glowing translucent bioluminescent jellyfish, wet-on-wet bleeding washes, deep ultramarine and turquoise pigment flows, visible cold-press paper grain, delicate light refraction, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['luminous watercolor painting', 'wet-on-wet bleeding washes', 'deep ultramarine and turquoise flows', 'visible cold-press paper grain']
      },
      {
        id: 'scene_f_03_impressionism',
        number: '03',
        nameCn: '印象派与点彩',
        nameEn: 'Impressionist Oil',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_f_03_impressionism.jpg',
        hasImage: true,
        tags: ['水下光斑颤动', '莫奈睡莲色调', '色彩碎笔混色', '幽暗波光'],
        master: '莫奈 (Monet) / 莫里索',
        colorTone: '深蓝、粉紫微光与青绿水波',
        technique: '运用莫奈《睡莲》晚期般的碎小光斑，表现深海水流晃动中的微弱生物荧光与探照灯漫射。',
        prompt: 'Impressionist oil painting of underwater bioluminescent jellyfish illuminating a deep sea diver, Claude Monet water lily reflection style, loose flickering brushstrokes, shimmering underwater light vibration, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['impressionist oil painting', 'Claude Monet style', 'loose flickering brushstrokes', 'shimmering underwater light vibration']
      },
      {
        id: 'scene_f_04_silkscreen',
        number: '04',
        nameCn: '丝网版画 / 波普艺术',
        nameEn: 'Silkscreen / Pop Art',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_f_04_silkscreen.jpg',
        hasImage: true,
        tags: ['荧光色块套印', '深海波普', '印刷微错版', '视觉冲击'],
        master: '安迪·沃霍尔 (Andy Warhol)',
        colorTone: '荧光青、荧光洋红与深黑深渊',
        technique: '高饱和荧光油墨多色孔版丝网套印，打造宛如现代艺术馆展出般的深海视觉海报。',
        prompt: 'Silkscreen screenprint pop art of a deep sea diver and giant glowing jellyfish in the ocean abyss, Andy Warhol graphic poster aesthetic, bold fluorescent cyan and magenta color blocks, slight misregistration print offset, high contrast, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['silkscreen screenprint pop art', 'Andy Warhol graphic poster aesthetic', 'bold fluorescent cyan and magenta color blocks', 'high contrast']
      },
      {
        id: 'scene_f_05_ukiyoe',
        number: '05',
        nameCn: '浮世绘木刻版画',
        nameEn: 'Japanese Ukiyo-e',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_f_05_ukiyoe.jpg',
        hasImage: true,
        tags: ['传统海女/海龙', '巨浪波纹', '木版套色', '和风水怪传说'],
        master: '葛饰北斋 / 歌川国芳',
        colorTone: '普鲁士深蓝 (Bero-ai)、朱砂与和纸米白',
        technique: '以《神奈川冲浪里》般遒劲有力的黑墨水纹勾线，呈现古典和风深海奇幻意境。',
        prompt: 'Authentic Japanese Ukiyo-e woodblock print of a traditional pearl diver surrounded by fantastical glowing sea jellyfish under dark waves, crisp black sumi-e outlines, flat Prussian blue mineral washes, washi paper texture, Hokusai style, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['Japanese Ukiyo-e woodblock print', 'crisp black sumi-e outlines', 'flat Prussian blue mineral washes', 'washi paper texture', 'Hokusai style']
      },
      {
        id: 'scene_f_06_vintage_comic',
        number: '06',
        nameCn: '美漫复古网点',
        nameEn: 'Vintage Comic / Ben-Day Dots',
        category: 'printmaking',
        categoryName: '版画印刷',
        image: 'images/scene_f_06_vintage_comic.jpg',
        hasImage: true,
        tags: ['海底两万里科幻', '本戴网点光芒', '美漫分镜', '复古探险'],
        master: '罗伊·利希滕斯坦 (Roy Lichtenstein)',
        colorTone: 'CMYK 原色系、荧光青与暗红',
        technique: '60年代经典海底惊险探险漫画风格，网点交织表现幽暗深海中的探照灯光束与发光触手。',
        prompt: 'Vintage 1960s comic book illustration of an undersea explorer encountering giant glowing alien jellyfish in deep trench, Roy Lichtenstein style, prominent Ben-Day halftone dots, bold black ink contour lines, retro sci-fi comic panel, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['vintage 1960s comic book illustration', 'Roy Lichtenstein style', 'prominent Ben-Day halftone dots', 'bold black ink contour lines']
      },
      {
        id: 'scene_f_07_citypop',
        number: '07',
        nameCn: 'City Pop 昭和复古',
        nameEn: '1980s City Pop Aesthetic',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_f_07_citypop.jpg',
        hasImage: true,
        tags: ['复古水族馆', '霓虹水光', '干净几何硬影', '昭和度假感'],
        master: '永井博 (Hiroshi Nagai)',
        colorTone: '湖水蓝、粉紫微光、珊瑚橙与纯白',
        technique: '充满 80 年代都会假期的水族馆浪漫感，平整无暇的渐变与清澈通透的水下几何光影。',
        prompt: '1980s Japanese City Pop aesthetic illustration by Hiroshi Nagai, an underwater resort aquarium view with a retro diver and neon glowing jellyfish, pastel blue gradients, clean flat shadows, retro futuristic aquatic mood, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['1980s Japanese City Pop aesthetic', 'Hiroshi Nagai style', 'pastel blue gradients', 'clean flat shadows', 'retro futuristic aquatic mood']
      },
      {
        id: 'scene_f_08_artnouveau',
        number: '08',
        nameCn: '新艺术运动',
        nameEn: 'Art Nouveau Masterpiece',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_f_08_artnouveau.jpg',
        hasImage: true,
        tags: ['优雅水母触手', '海百合装饰框', '流动自然曲线', '烫金点缀'],
        master: '阿尔丰斯·慕夏 (Alphonse Mucha)',
        colorTone: '香槟金、海蓝宝石、珊瑚粉与象牙白',
        technique: '水母优雅缠绕的修长触手化为新艺术运动经典的流动阿拉伯花纹，环绕对称水下生灵装饰框。',
        prompt: 'Art Nouveau masterpiece illustration of a diver surrounded by sinuous tentacles of glowing jellyfish in underwater coral garden, Alphonse Mucha style, flowing organic curves, intricate sea lily decorative border, golden accents, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['Art Nouveau masterpiece illustration', 'Alphonse Mucha style', 'flowing organic curves', 'intricate sea lily decorative border', 'golden accents']
      },
      {
        id: 'scene_f_09_artdeco',
        number: '09',
        nameCn: '装饰风艺术',
        nameEn: 'Art Deco Ocean Floor',
        category: 'retro_pop',
        categoryName: '时代美学',
        image: 'images/scene_f_09_artdeco.jpg',
        hasImage: true,
        tags: ['几何铜盔', '对称发光水母', '深蓝曜金', '流线型奢华'],
        master: 'Tamara de Lempicka',
        colorTone: '深海夜蓝、金属黄铜金与亮青',
        technique: '严谨几何对称构图，将深海潜水服与水母生物结构转化为极具现代奢华感的装饰风纹样。',
        prompt: '1920s Art Deco illustration of an underwater exploration diver with geometric bronze helmet and stylized glowing jellyfish, luxurious deep navy and metallic gold palette, sleek streamlined symmetry, Great Gatsby ocean aesthetic, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['1920s Art Deco illustration', 'luxurious deep navy and metallic gold palette', 'sleek streamlined symmetry', 'Great Gatsby ocean aesthetic']
      },
      {
        id: 'scene_f_10_cyberpunk',
        number: '10',
        nameCn: '赛博朋克霓虹',
        nameEn: 'Cyberpunk Abyss',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_f_10_cyberpunk.jpg',
        hasImage: true,
        tags: ['生化合成水母', '深海机甲潜水员', '霓虹光纤触须', '海底高科技'],
        master: '《攻壳机动队》 / 《银翼杀手》',
        colorTone: '荧光青、品红激光束与深渊纯黑',
        technique: '深海成为未来赛博深渊，人造光纤水母与高科技机甲潜水员在暗夜中散发璀璨霓虹脉冲。',
        prompt: 'Cyberpunk sci-fi illustration of a high-tech robotic deep-sea submersible diver navigating through swarms of synthetic neon-glowing jellyfish in dark oceanic trench, cyan and magenta bioluminescence, Blade Runner underwater, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['Cyberpunk sci-fi illustration', 'synthetic neon-glowing jellyfish', 'cyan and magenta bioluminescence', 'Blade Runner underwater']
      },
      {
        id: 'scene_f_11_ghibli',
        number: '11',
        nameCn: '吉卜力 / 赛璐珞平涂',
        nameEn: 'Studio Ghibli Deep Sea',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_f_11_ghibli.jpg',
        hasImage: true,
        tags: ['悬崖上的金鱼姬画风', '梦幻发光水母', '手绘宁静海洋', '治愈清新'],
        master: '男鹿和雄 / 宫崎骏 (Ponyo)',
        colorTone: '澄澈海蓝、梦幻浅粉与水草嫩绿',
        technique: '致敬《悬崖上的金鱼姬》水下世界，温柔治愈的水粉手绘质感与温和平静的深海生命力。',
        prompt: 'Studio Ghibli style cel-shaded anime background of a diver floating peacefully alongside gentle giant glowing jellyfish in a deep magical sea, Hayao Miyazaki Ponyo underwater aesthetic, painterly blue depths, whimsical glowing spores, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['Studio Ghibli style', 'Hayao Miyazaki Ponyo aesthetic', 'painterly blue depths', 'whimsical glowing spores']
      },
      {
        id: 'scene_f_12_flatvector',
        number: '12',
        nameCn: '极简扁平矢量',
        nameEn: 'Minimalist Jellyfish Vector',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_f_12_flatvector.jpg',
        hasImage: true,
        tags: ['潜水员剪影', '极简发光水母', '深邃负空间', '现代图形设计'],
        master: 'Malika Favre',
        colorTone: '午夜深蓝、荧光青与纯白反光',
        technique: '极致纯粹的负空间设计，用极其精简的几何形体表现潜水员与巨大水母的体量对比。',
        prompt: 'Minimalist flat vector illustration of a diver silhouette exploring near a giant glowing jellyfish in deep blue sea, Malika Favre style, bold negative space, high contrast silhouette, clean geometric vector shapes, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['Minimalist flat vector illustration', 'Malika Favre style', 'bold negative space', 'high contrast silhouette', 'clean geometric vector shapes']
      },
      {
        id: 'scene_f_13_pixelart',
        number: '13',
        nameCn: '16-bit 像素风',
        nameEn: '16-bit Deep Sea Odyssey',
        category: 'digital',
        categoryName: '现代数码',
        image: 'images/scene_f_13_pixelart.jpg',
        hasImage: true,
        tags: ['复古水下关卡', '点阵自发光水母', '深海水滴颗粒', '16-bit 探险'],
        master: 'SNES 黄金时代水下像素神作',
        colorTone: '16-bit 深海蓝紫与荧光亮绿点阵',
        technique: '细腻像素点阵抖动表现水母的透明光晕与水泡上升动感，极富 90 年代经典游戏质感。',
        prompt: '16-bit pixel art of a deep sea diver encountering giant glowing jellyfish in dark ocean trench, nostalgic retro underwater game aesthetic, vibrant blue and purple pixel dithering, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['16-bit pixel art', 'nostalgic retro underwater game aesthetic', 'vibrant blue and purple pixel dithering']
      },
      {
        id: 'scene_f_14_crayon',
        number: '14',
        nameCn: '绘本蜡笔与拼贴',
        nameEn: 'Picture Book / Crayon Collage',
        category: 'fine_art',
        categoryName: '传统画种',
        image: 'images/scene_f_14_crayon.jpg',
        hasImage: true,
        tags: ['彩色发光小水母', '蜡笔波浪', '手工剪纸', '童趣深海'],
        master: 'Eric Carle / Leo Lionni',
        colorTone: '天真水蓝、亮彩蜡笔粉与阳光暖黄',
        technique: '手工水彩刮色纸拼贴与凹凸蜡笔质感，将深海变成充满童趣与温柔探索的童话绘本。',
        prompt: 'Children\'s picture book illustration in Eric Carle style, a friendly little diver swimming with colorful glowing jellyfish in deep blue sea, rich waxy crayon textures, hand-painted textured paper collage, cheerful naive art, 16:9 aspect ratio --ar 16:9',
        keyModifiers: ['Children\'s picture book illustration', 'Eric Carle style', 'rich waxy crayon textures', 'hand-painted textured paper collage', 'cheerful naive art']
      }
    ]
  }
];
